packages:
  - "packages/*"
  - "apps/*"
  - "apps/showcase/*"
  - "apps/hello/*"
  - "apps/perf/*"
  - "apps/bevy/*"
  - "apps/shadertoy/*"
  - "apps/parity/*"
  - "apps/learn-render/*/*"
  - "apps/learn-render/*/*/*"
  - "tools/view"
  - "tools/view/packages/*"
  - "templates/empty"
  - "templates/game-3d"

allowBuilds:
  '@forgeax/engine-dawn-node': true
  esbuild: true
  simple-git-hooks: true
  webgpu: true

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl

linkWorkspacePackages: true
minimumReleaseAgeExclude:
  - "@forgeax/*"
overrides:
  fast-uri: 3.1.7
