import {init,buildFromPolygon} from '@matthewjacobson/str8';
import earcut from 'earcut';
import {footprints} from '../../assets/footprints.ts';
import {writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
await init();const results={},errors=[];let maxRelativeAreaError=0;
for(const row of footprints){
 if(row.width>130||row.depth>130||row.label.includes('墙'))continue;
 try{
  const p=row.polygon.map(([x,z])=>[x-row.x,z-row.z]);const s=buildFromPolygon([p]);if(!s)throw Error('no skeleton');
  const vertices=Array.from(s.vertices),triangles=[],edgeCounts=new Map();
  for(const face of s.faces){
   const flat=face.flatMap(i=>[vertices[i*3],vertices[i*3+1]]);triangles.push(...earcut(flat).map(i=>face[i]));
   for(let i=0;i<face.length;i++){const a=face[i],b=face[(i+1)%face.length],key=[Math.min(a,b),Math.max(a,b)].join(',');edgeCounts.set(key,(edgeCounts.get(key)??0)+1);}
  }
  let area=0,roofArea=0;for(let i=0;i<p.length-1;i++)area+=p[i][0]*p[i+1][1]-p[i+1][0]*p[i][1];area=Math.abs(area/2);
  for(let i=0;i<triangles.length;i+=3){const [a,b,c]=triangles.slice(i,i+3).map(j=>j*3);roofArea+=Math.abs((vertices[b]-vertices[a])*(vertices[c+1]-vertices[a+1])-(vertices[b+1]-vertices[a+1])*(vertices[c]-vertices[a]))/2;}
  const relativeAreaError=Math.abs(roofArea-area)/area;maxRelativeAreaError=Math.max(maxRelativeAreaError,relativeAreaError);if(relativeAreaError>.001)throw Error('partition area mismatch '+relativeAreaError);
  results[row.id]={vertices,triangles,ridges:[...edgeCounts].filter(([,n])=>n===2).flatMap(([key])=>key.split(',').map(Number))};
 }catch(e){errors.push({id:row.id,label:row.label,error:String(e)});}
}
if(errors.length)throw Error(JSON.stringify(errors));
const sourceDigest=createHash('sha256').update(JSON.stringify(footprints)).digest('hex');
const header='// Generated by tools/roof-authoring/generate.mjs from OSM footprints; see docs/sources.md.\n';
const declaration='export const roofPartitions:Record<number,{vertices:number[];triangles:number[];ridges:number[]}> = {\n';
const rows=Object.entries(results).map(([id,value])=>'  '+JSON.stringify(id)+':'+JSON.stringify(value)).join(',\n');
writeFileSync(new URL('../../assets/roof-partitions.ts',import.meta.url),header+'export const roofFootprintDigest='+JSON.stringify(sourceDigest)+';\n'+declaration+rows+'\n};\n');
console.log(JSON.stringify({count:Object.keys(results).length,sourceDigest,maxRelativeAreaError}));
