import {World,createWorldContext} from '@forgeax/engine/ecs';
import {AssetRegistry} from '@forgeax/engine/assets-runtime';
import {ShaderRegistry} from '@forgeax/engine/shader';
import {SceneInstance} from '@forgeax/engine/render';
import {Transform} from '@forgeax/engine/scene';
import {physicsPlugin} from '@forgeax/engine/physics';
import {createNavigationMesh,navigationCharacterPlugin,NavigationCharacter,NavigationAgent,NavigationAgentStatus,setNavigationTarget} from '@forgeax/engine/navigation';
export const navGuid='080872b5-5681-5138-94a1-ef74b0717c7f',sceneGuid='a1cceae6-7f55-5e30-81a0-62bc65db5635';
export async function loadNavigationScene(registry,world){registry.configurePackIndex(new URL('/pack-index.json',location.href).href);const asset=(await registry.loadByGuid(registry.parseGuid(navGuid))).unwrap(),scene=(await registry.loadByGuid(registry.parseGuid(sceneGuid))).unwrap(),mesh=createNavigationMesh(asset).unwrap();return {asset,scene,mesh};}
export async function runWorkerSimulation(){const registry=new AssetRegistry(new ShaderRegistry({manifestUrl:undefined})),world=new World();const {asset,scene,mesh}=await loadNavigationScene(registry,world);const ctx=await createWorldContext(world,[physicsPlugin('rapier-3d'),navigationCharacterPlugin(mesh)]);world.components.register(SceneInstance).unwrap();try{registry.instantiateFlat(world.allocSharedRef('SceneAsset',scene),world).unwrap();const entities=Array.from(world.query({with:[NavigationCharacter]}).unwrap(),r=>r.entity),starts=entities.map(e=>[...world.get(e,Transform).unwrap().pos]);for(let i=0;i<entities.length;i++)setNavigationTarget(world,entities[i],[-starts[i][0],0,-starts[i][2]],{maxProjection:.3}).unwrap();for(let i=0;i<900;i++)world.update(1/60).unwrap();return {sourceDigest:asset.sourceDigest,frames:900,states:entities.map(e=>({position:[...world.get(e,Transform).unwrap().pos],status:world.get(e,NavigationAgent).unwrap().status})),arrived:entities.every((e,i)=>{const p=world.get(e,Transform).unwrap().pos;return world.get(e,NavigationAgent).unwrap().status===NavigationAgentStatus.arrived&&Math.hypot(p[0]+starts[i][0],p[2]+starts[i][2])<=.081;})};}finally{await ctx.fiber.dispose();}}
