//! Native evidence for the render `WorldTraversal` seam.
//!
//! The fixtures are generated by `@forgeax/engine-render`
//! (`world-traversal.unit.test.ts` fails when they drift), so this test runs the exact
//! WGSL the renderer composes: one parity kernel per traversal with the same body
//! (`traceWorld` + `worldCardRadiance`), against one analytic box scene. Ray Query traces
//! a TLAS of 12-triangle unit boxes; the Global SDF lane traces voxels composed on the GPU
//! by the production compose shader from per-instance dense fields. Both shade through
//! the same Cards. A CPU ray/OBB oracle is the reference for both.

use crate::acceleration::tests::{gpu, Gpu};
use crate::acceleration::{
    build_acceleration_structures, create_blas, create_tlas, BlasBuild, BlasDescriptor,
    BuildPreference, TlasBuild, TlasDescriptor, TlasInstance, TriangleGeometry,
    TriangleGeometrySize, UpdateMode,
};
use glam::{Mat4, Quat, Vec3, Vec3Swizzles, Vec4Swizzles};
use std::sync::mpsc;
use std::time::Duration;
use wgpu::util::{BufferInitDescriptor, DeviceExt};

const FIXTURES: [(&str, &str); 7] = [
    (
        "global-sdf.wgsl",
        include_str!("__tests__/fixtures/world-traversal/global-sdf.wgsl"),
    ),
    (
        "ray-query.wgsl",
        include_str!("__tests__/fixtures/world-traversal/ray-query.wgsl"),
    ),
    (
        "compose.wgsl",
        include_str!("__tests__/fixtures/world-traversal/compose.wgsl"),
    ),
    (
        "card-surface.ray-query.wgsl",
        include_str!("__tests__/fixtures/world-traversal/card-surface.ray-query.wgsl"),
    ),
    (
        "trace-probes.ray-query.wgsl",
        include_str!("__tests__/fixtures/world-traversal/trace-probes.ray-query.wgsl"),
    ),
    (
        "trace-reflections.ray-query.wgsl",
        include_str!("__tests__/fixtures/world-traversal/trace-reflections.ray-query.wgsl"),
    ),
    (
        "screen-probe-world.ray-query.wgsl",
        include_str!("__tests__/fixtures/world-traversal/screen-probe-world.ray-query.wgsl"),
    ),
];

fn fixture(name: &str) -> &'static str {
    FIXTURES.iter().find(|(n, _)| *n == name).unwrap().1
}

const SPACING: f32 = 0.125;
const DIMS: u32 = 66;
const ORIGIN: f32 = -4.125;
const FIELD_DIM: u32 = 17;
const FIELD_LO: f32 = -0.75;
const FIELD_SPACING: f32 = 1.5 / 16.0;
const RES: u32 = 4;
const ATLAS: (u32, u32) = (64, 16);
const MAX_STEPS: u32 = 256;
const MIN_STEP_FACTOR: f32 = 0.25;
const MARGIN: f32 = 0.5 * SPACING;
const STATUS_HIT: u32 = 1;

#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct GpuInstance {
    inverse: [f32; 16],
    ids: [u32; 4],
    field: [u32; 4],
    origin: [f32; 4],
    extent: [f32; 4],
    error: [f32; 4],
}

#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct GpuBounds {
    lo: [f32; 4],
    hi: [f32; 4],
    scale: [f32; 4],
}

#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct GpuGrid {
    origin_spacing: [f32; 4],
    dimensions_count: [u32; 4],
    ranges: [f32; 4],
}

#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct GpuCard {
    origin: [f32; 4],
    u: [f32; 4],
    v: [f32; 4],
    n: [f32; 4],
    ids: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct GpuRay {
    origin: [f32; 3],
    t_min: f32,
    direction: [f32; 3],
    t_max: f32,
    mask: [u32; 4],
}

#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
struct Traced {
    state: [u32; 4],
    metrics: [f32; 4],
    position: [f32; 4],
    normal: [f32; 4],
    radiance: [f32; 4],
}

/// A unit box ([-0.5, 0.5]^3) under `transform = T * R * S`.
struct Box3 {
    id: u32,
    transform: Mat4,
    mask: u8,
}

fn placed(id: u32, center: [f32; 3], scale: [f32; 3], rotation: Quat) -> Box3 {
    Box3 {
        id,
        transform: Mat4::from_scale_rotation_translation(
            Vec3::from(scale),
            rotation,
            Vec3::from(center),
        ),
        mask: 0x01,
    }
}

/// A closed room: interior [-3, 3]^3, walls 0.5 thick.
fn room() -> Vec<Box3> {
    let none = Quat::IDENTITY;
    vec![
        placed(100, [0.0, -3.25, 0.0], [7.0, 0.5, 7.0], none),
        placed(101, [0.0, 3.25, 0.0], [7.0, 0.5, 7.0], none),
        placed(102, [-3.25, 0.0, 0.0], [0.5, 7.0, 7.0], none),
        placed(103, [3.25, 0.0, 0.0], [0.5, 7.0, 7.0], none),
        placed(104, [0.0, 0.0, -3.25], [7.0, 7.0, 0.5], none),
        placed(105, [0.0, 0.0, 3.25], [7.0, 7.0, 0.5], none),
    ]
}

fn furnished() -> Vec<Box3> {
    let mut boxes = room();
    boxes.push(placed(
        200,
        [1.2, -2.0, 0.6],
        [1.0, 2.0, 0.8],
        Quat::from_rotation_y(35f32.to_radians()),
    ));
    boxes.push(placed(
        201,
        [-1.5, -2.5, -0.8],
        [1.0, 1.0, 1.0],
        Quat::from_rotation_x(20f32.to_radians()),
    ));
    boxes.push(placed(
        202,
        [-0.5, 1.2, 1.8],
        [1.6, 0.3, 0.6],
        Quat::from_axis_angle(Vec3::new(1.0, 1.0, 0.0).normalize(), 25f32.to_radians()),
    ));
    boxes
}

const PLATE_X: f32 = 0.0625;
const PLATE_THICKNESS: f32 = 0.02;
const PLATE_ID: u32 = 300;

/// The room split by a 0.02-thick plate between two voxel columns.
fn partitioned(plate_mask: u8) -> Vec<Box3> {
    let mut boxes = room();
    let mut plate = placed(
        PLATE_ID,
        [PLATE_X, 0.0, 0.0],
        [PLATE_THICKNESS, 7.0, 7.0],
        Quat::IDENTITY,
    );
    plate.mask = plate_mask;
    boxes.push(plate);
    boxes
}

fn box_sdf(p: Vec3) -> f32 {
    let q = p.abs() - Vec3::splat(0.5);
    q.max(Vec3::ZERO).length() + q.max_element().min(0.0)
}

fn axis_scales(m: &Mat4) -> Vec3 {
    Vec3::new(
        m.x_axis.xyz().length(),
        m.y_axis.xyz().length(),
        m.z_axis.xyz().length(),
    )
}

/// Faces in Card order: axis-major, + before -.
fn faces() -> impl Iterator<Item = (usize, f32)> {
    (0..3).flat_map(|a| [(a, 1.0), (a, -1.0)])
}

fn face_index(axis: usize, sign: f32) -> usize {
    axis * 2 + usize::from(sign < 0.0)
}

fn card_color(card: usize) -> [f32; 4] {
    let c = card as f32;
    [
        (c + 1.0) / 64.0,
        ((card * 7) % 64 + 1) as f32 / 64.0,
        ((card * 13) % 64 + 1) as f32 / 64.0,
        1.0,
    ]
}

#[derive(Clone, Copy, Debug)]
struct Expected {
    t: f32,
    instance: u32,
    normal: Vec3,
    card: usize,
    /// The entry lies within 1e-4 of an edge: face and Card are ambiguous.
    edge: bool,
}

/// CPU reference: nearest entering face of any box with `mask & ray.mask != 0`.
fn oracle(boxes: &[Box3], ray: &GpuRay) -> Option<Expected> {
    let origin = Vec3::from(ray.origin);
    let direction = Vec3::from(ray.direction);
    let mut best: Option<Expected> = None;
    for (index, b) in boxes.iter().enumerate() {
        if u32::from(b.mask) & ray.mask[0] == 0 {
            continue;
        }
        let inverse = b.transform.inverse();
        let o = inverse.transform_point3(origin);
        let d = inverse.transform_vector3(direction);
        let (mut near, mut far, mut axis, mut second) =
            (f32::NEG_INFINITY, f32::INFINITY, 0, f32::NEG_INFINITY);
        let mut inside = true;
        for a in 0..3 {
            if d[a].abs() < 1e-12 {
                inside &= o[a].abs() <= 0.5;
                continue;
            }
            let (t0, t1) = ((-0.5 - o[a]) / d[a], (0.5 - o[a]) / d[a]);
            let entry = t0.min(t1);
            if entry > near {
                second = near;
                near = entry;
                axis = a;
            } else if entry > second {
                second = entry;
            }
            far = far.min(t0.max(t1));
        }
        if !inside || near > far || near <= ray.t_min || near >= ray.t_max {
            continue;
        }
        if best.is_some_and(|e| e.t <= near) {
            continue;
        }
        let sign = -d[axis].signum();
        let mut local = Vec3::ZERO;
        local[axis] = sign;
        best = Some(Expected {
            t: near,
            instance: b.id,
            normal: b.transform.transform_vector3(local).normalize(),
            card: index * 6 + face_index(axis, sign),
            edge: (near - second).abs() <= 1e-4 * near.max(1.0),
        });
    }
    best
}

struct Scene {
    boxes: Vec<Box3>,
    instances: wgpu::Buffer,
    fields: wgpu::Buffer,
    bounds: wgpu::Buffer,
    grid: wgpu::Buffer,
    voxels: wgpu::Buffer,
    cards: wgpu::Buffer,
    card_lit: wgpu::Buffer,
    textures: Vec<wgpu::TextureView>,
    traversal_instances: wgpu::Buffer,
    face_normals: wgpu::Buffer,
    tlas: crate::acceleration::Tlas,
    /// `settings.z`: Card residency has pending (non-resident) instances.
    residency_pending: u32,
}

fn storage(gpu: &Gpu, label: &str, contents: &[u8]) -> wgpu::Buffer {
    gpu.device.create_buffer_init(&BufferInitDescriptor {
        label: Some(label),
        contents,
        usage: wgpu::BufferUsages::STORAGE,
    })
}

fn uniform(gpu: &Gpu, label: &str, contents: &[u8]) -> wgpu::Buffer {
    gpu.device.create_buffer_init(&BufferInitDescriptor {
        label: Some(label),
        contents,
        usage: wgpu::BufferUsages::UNIFORM,
    })
}

fn octahedral(n: Vec3) -> [f32; 2] {
    let p = n.xy() / (n.x.abs() + n.y.abs() + n.z.abs());
    if n.z >= 0.0 {
        return p.into();
    }
    let sign = |v: f32| if v >= 0.0 { 1.0 } else { -1.0 };
    [(1.0 - p.y.abs()) * sign(p.x), (1.0 - p.x.abs()) * sign(p.y)]
}

fn unit_box() -> ([[f32; 3]; 8], [u32; 36]) {
    let mut vertices = [[0.0; 3]; 8];
    for (i, v) in vertices.iter_mut().enumerate() {
        *v = [0, 1, 2].map(|a| if i >> a & 1 == 1 { 0.5 } else { -0.5 });
    }
    // Outward counter-clockwise quads per face (vertex bit a = +a).
    let quads: [[u32; 4]; 6] = [
        [1, 3, 7, 5],
        [0, 4, 6, 2],
        [2, 6, 7, 3],
        [0, 1, 5, 4],
        [4, 5, 7, 6],
        [0, 2, 3, 1],
    ];
    let mut indices = [0; 36];
    for (f, q) in quads.iter().enumerate() {
        indices[f * 6..f * 6 + 6].copy_from_slice(&[q[0], q[1], q[2], q[0], q[2], q[3]]);
    }
    (vertices, indices)
}

/// `pending` names instances whose Card rows are installed but not yet captured
/// (`ids.y = 2`, Card residency); any of them turns the residency flag on.
fn build_scene(gpu: &Gpu, boxes: Vec<Box3>, pending: &[u32]) -> Scene {
    let device = &gpu.device;
    let count = boxes.len() as u32;
    let field_words = (FIELD_DIM * FIELD_DIM * FIELD_DIM) as usize;
    let mut fields = Vec::with_capacity(field_words * boxes.len());
    let mut instances = Vec::new();
    let mut bounds = Vec::new();
    for (i, b) in boxes.iter().enumerate() {
        for z in 0..FIELD_DIM {
            for y in 0..FIELD_DIM {
                for x in 0..FIELD_DIM {
                    let p = Vec3::new(x as f32, y as f32, z as f32) * FIELD_SPACING
                        + Vec3::splat(FIELD_LO);
                    fields.push(box_sdf(p).to_bits());
                }
            }
        }
        let scale = axis_scales(&b.transform);
        instances.push(GpuInstance {
            inverse: b.transform.inverse().to_cols_array(),
            ids: [b.id, 0, 0, u32::from(b.mask)],
            field: [(i * field_words) as u32, FIELD_DIM, FIELD_DIM, FIELD_DIM],
            origin: [FIELD_LO, FIELD_LO, FIELD_LO, FIELD_SPACING],
            extent: [-FIELD_LO, -FIELD_LO, -FIELD_LO, 1.0],
            error: [0.0; 4],
        });
        bounds.push(GpuBounds {
            lo: [-0.5, -0.5, -0.5, 0.0],
            hi: [0.5, 0.5, 0.5, 0.0],
            scale: [scale.x, scale.y, scale.z, scale.min_element()],
        });
    }
    let grid = GpuGrid {
        origin_spacing: [ORIGIN, ORIGIN, ORIGIN, SPACING],
        dimensions_count: [DIMS, DIMS, DIMS, count],
        ranges: [2.0, SPACING, 0.0, 0.0],
    };
    let voxel_count = (DIMS * DIMS * DIMS) as u64;
    let scene_instances = storage(gpu, "parity.instances", bytemuck::cast_slice(&instances));
    let scene_fields = storage(gpu, "parity.fields", bytemuck::cast_slice(&fields));
    let scene_bounds = storage(gpu, "parity.bounds", bytemuck::cast_slice(&bounds));
    let scene_grid = uniform(gpu, "parity.grid", bytemuck::bytes_of(&grid));
    let voxels = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("parity.voxels"),
        size: voxel_count * 16,
        usage: wgpu::BufferUsages::STORAGE,
        mapped_at_creation: false,
    });

    // Cards: one per box face, one RES^2 atlas tile each, a distinct lit color per Card.
    let tiles_per_row = (ATLAS.0 / RES) as usize;
    assert!(boxes.len() * 6 <= tiles_per_row * (ATLAS.1 / RES) as usize);
    let texels = (ATLAS.0 * ATLAS.1) as usize;
    let mut cards = Vec::new();
    let mut card_lit = vec![[0f32; 4]; texels];
    let mut normal = vec![0i8; texels * 4];
    let mut f0 = vec![0u8; texels * 4];
    for b in &boxes {
        for (axis, sign) in faces() {
            let card = cards.len();
            let (u_axis, v_axis) = ((axis + 1) % 3, (axis + 2) % 3);
            let mut local = Vec3::ZERO;
            local[axis] = sign * 0.5;
            local[u_axis] = -0.5;
            local[v_axis] = -0.5;
            let along = |a: usize| {
                let mut e = Vec3::ZERO;
                e[a] = 1.0;
                b.transform.transform_vector3(e)
            };
            let (u, v) = (along(u_axis), along(v_axis));
            let n = (along(axis) * sign).normalize();
            cards.push(GpuCard {
                origin: b.transform.transform_point3(local).extend(1.0).into(),
                u: u.normalize().extend(u.length()).into(),
                v: v.normalize().extend(v.length()).into(),
                n: n.extend(1.0).into(),
                ids: [b.id, if pending.contains(&b.id) { 2 } else { 1 }, 0, 0],
            });
            let octa = octahedral(n).map(|c| (c * 127.0).round() as i8);
            let tile = (
                (card % tiles_per_row) * RES as usize,
                (card / tiles_per_row) * RES as usize,
            );
            for y in 0..RES as usize {
                for x in 0..RES as usize {
                    let texel = (tile.1 + y) * ATLAS.0 as usize + tile.0 + x;
                    card_lit[texel] = card_color(card);
                    normal[texel * 4..texel * 4 + 4]
                        .copy_from_slice(&[octa[0], octa[1], octa[0], octa[1]]);
                    f0[texel * 4 + 3] = 255;
                }
            }
        }
    }
    let texture = |label: &str, format: wgpu::TextureFormat, data: &[u8]| {
        device
            .create_texture_with_data(
                &gpu.queue,
                &wgpu::TextureDescriptor {
                    label: Some(label),
                    size: wgpu::Extent3d {
                        width: ATLAS.0,
                        height: ATLAS.1,
                        depth_or_array_layers: 1,
                    },
                    mip_level_count: 1,
                    sample_count: 1,
                    dimension: wgpu::TextureDimension::D2,
                    format,
                    usage: wgpu::TextureUsages::TEXTURE_BINDING,
                    view_formats: &[],
                },
                wgpu::util::TextureDataOrder::LayerMajor,
                data,
            )
            .create_view(&Default::default())
    };
    let zero = vec![0u8; texels * 4];
    let depth = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("parity.card-depth"),
        size: wgpu::Extent3d {
            width: ATLAS.0,
            height: ATLAS.1,
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Depth32Float,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::RENDER_ATTACHMENT,
        view_formats: &[],
    });
    let depth_view = depth.create_view(&Default::default());
    let textures = vec![
        texture("parity.albedo", wgpu::TextureFormat::Rgba8Unorm, &zero),
        texture(
            "parity.normal",
            wgpu::TextureFormat::Rgba8Snorm,
            bytemuck::cast_slice(&normal),
        ),
        texture("parity.emission", wgpu::TextureFormat::Rgba8Unorm, &zero),
        texture("parity.f0", wgpu::TextureFormat::Rgba8Unorm, &f0),
        depth_view,
    ];

    // Ray Query inputs: one BLAS for the unit box, one TLAS row per instance.
    let (vertices, indices) = unit_box();
    let face_normals: Vec<[f32; 4]> = indices
        .chunks_exact(3)
        .map(|t| {
            let p: Vec<Vec3> = t
                .iter()
                .map(|&i| Vec3::from(vertices[i as usize]))
                .collect();
            (p[1] - p[0])
                .cross(p[2] - p[0])
                .normalize()
                .extend(0.0)
                .into()
        })
        .collect();
    let vertex_buffer = device.create_buffer_init(&BufferInitDescriptor {
        label: Some("parity.box-vertices"),
        contents: bytemuck::cast_slice(&vertices),
        usage: wgpu::BufferUsages::BLAS_INPUT,
    });
    let index_buffer = device.create_buffer_init(&BufferInitDescriptor {
        label: Some("parity.box-indices"),
        contents: bytemuck::cast_slice(&indices),
        usage: wgpu::BufferUsages::BLAS_INPUT,
    });
    let blas = create_blas(
        device,
        &gpu.caps,
        &BlasDescriptor {
            label: Some("parity.box"),
            geometries: vec![TriangleGeometrySize {
                vertex_count: 8,
                index: Some((wgpu::IndexFormat::Uint32, 36)),
            }],
            preference: BuildPreference::FastTrace,
            update_mode: UpdateMode::Rebuild,
        },
    )
    .unwrap();
    let mut tlas = create_tlas(
        device,
        &gpu.caps,
        &TlasDescriptor {
            label: Some("parity.tlas"),
            max_instances: count,
            preference: BuildPreference::FastTrace,
            update_mode: UpdateMode::Rebuild,
        },
    )
    .unwrap();
    let rows: Vec<[u32; 4]> = std::iter::once([0; 4])
        .chain(boxes.iter().map(|b| [b.id, 0, 0, 0]))
        .collect();
    let mut encoder = device.create_command_encoder(&Default::default());
    build_acceleration_structures(
        &mut encoder,
        &[BlasBuild {
            blas: &blas,
            geometries: vec![TriangleGeometry {
                vertex_buffer: &vertex_buffer,
                first_vertex: 0,
                vertex_stride: 12,
                index: Some((&index_buffer, 0)),
            }],
        }],
        &mut [TlasBuild {
            tlas: &mut tlas,
            instances: boxes
                .iter()
                .enumerate()
                .map(|(row, b)| {
                    let m = b.transform.transpose().to_cols_array();
                    TlasInstance {
                        blas: &blas,
                        // Rows of the column-major affine transform.
                        transform: std::array::from_fn(|k| m[k]),
                        custom_index: row as u32 + 1,
                        mask: b.mask,
                    }
                })
                .collect(),
        }],
    )
    .unwrap();
    // Card depth 0 = the face plane itself.
    drop(encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
        label: Some("parity.card-depth-clear"),
        color_attachments: &[],
        depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
            view: &textures[4],
            depth_ops: Some(wgpu::Operations {
                load: wgpu::LoadOp::Clear(0.0),
                store: wgpu::StoreOp::Store,
            }),
            stencil_ops: None,
        }),
        timestamp_writes: None,
        occlusion_query_set: None,
        multiview_mask: None,
    }));
    let compose = pipeline(gpu, fixture("compose.wgsl"));
    let bind = bind_group(
        gpu,
        &compose,
        &[
            (0, scene_instances.as_entire_binding()),
            (1, scene_fields.as_entire_binding()),
            (2, scene_bounds.as_entire_binding()),
            (3, scene_grid.as_entire_binding()),
            (4, voxels.as_entire_binding()),
        ],
    );
    {
        let mut pass = encoder.begin_compute_pass(&Default::default());
        pass.set_pipeline(&compose);
        pass.set_bind_group(0, Some(&bind), &[]);
        pass.dispatch_workgroups((voxel_count as u32).div_ceil(64), 1, 1);
    }
    gpu.queue.submit([encoder.finish()]);
    Scene {
        boxes,
        instances: scene_instances,
        fields: scene_fields,
        bounds: scene_bounds,
        grid: scene_grid,
        voxels,
        cards: storage(gpu, "parity.cards", bytemuck::cast_slice(&cards)),
        card_lit: storage(gpu, "parity.card-lit", bytemuck::cast_slice(&card_lit)),
        textures,
        traversal_instances: storage(
            gpu,
            "parity.traversal-instances",
            bytemuck::cast_slice(&rows),
        ),
        face_normals: storage(
            gpu,
            "parity.face-normals",
            bytemuck::cast_slice(&face_normals),
        ),
        tlas,
        residency_pending: u32::from(!pending.is_empty()),
    }
}

fn pipeline(gpu: &Gpu, source: &str) -> wgpu::ComputePipeline {
    let module = gpu
        .device
        .create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("parity"),
            source: wgpu::ShaderSource::Wgsl(source.into()),
        });
    gpu.device
        .create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("parity"),
            layout: None,
            module: &module,
            entry_point: Some("main"),
            compilation_options: Default::default(),
            cache: None,
        })
}

fn bind_group(
    gpu: &Gpu,
    pipeline: &wgpu::ComputePipeline,
    entries: &[(u32, wgpu::BindingResource<'_>)],
) -> wgpu::BindGroup {
    let entries: Vec<_> = entries
        .iter()
        .map(|(binding, resource)| wgpu::BindGroupEntry {
            binding: *binding,
            resource: resource.clone(),
        })
        .collect();
    gpu.device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("parity"),
        layout: &pipeline.get_bind_group_layout(0),
        entries: &entries,
    })
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Traversal {
    GlobalSdf,
    RayQuery,
}

fn trace(gpu: &Gpu, scene: &Scene, traversal: Traversal, rays: &[GpuRay]) -> Vec<Traced> {
    let device = &gpu.device;
    let size = (rays.len() * std::mem::size_of::<Traced>()) as u64;
    let ray_buffer = storage(gpu, "parity.rays", bytemuck::cast_slice(rays));
    let output = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("parity.traced"),
        size,
        usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
        mapped_at_creation: false,
    });
    let readback = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("parity.readback"),
        size,
        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    let parity = uniform(
        gpu,
        "parity.trace",
        bytemuck::bytes_of(&[MARGIN, MIN_STEP_FACTOR, 0.0, 0.0]),
    );
    let settings = uniform(
        gpu,
        "parity.settings",
        bytemuck::bytes_of(&[
            scene.boxes.len() as u32 * 6,
            RES,
            scene.residency_pending,
            MAX_STEPS,
        ]),
    );
    let source = match traversal {
        Traversal::GlobalSdf => fixture("global-sdf.wgsl"),
        Traversal::RayQuery => fixture("ray-query.wgsl"),
    };
    let kernel = pipeline(gpu, source);
    let mut entries = match traversal {
        Traversal::GlobalSdf => vec![
            (0, scene.voxels.as_entire_binding()),
            (1, scene.grid.as_entire_binding()),
            (2, scene.instances.as_entire_binding()),
            (3, scene.fields.as_entire_binding()),
            (4, scene.bounds.as_entire_binding()),
        ],
        Traversal::RayQuery => vec![
            (0, scene.tlas.binding()),
            (2, scene.traversal_instances.as_entire_binding()),
            (3, scene.face_normals.as_entire_binding()),
        ],
    };
    entries.extend([
        (5, scene.cards.as_entire_binding()),
        (6, scene.card_lit.as_entire_binding()),
        (7, ray_buffer.as_entire_binding()),
        (8, output.as_entire_binding()),
        (9, parity.as_entire_binding()),
        (10, settings.as_entire_binding()),
    ]);
    for (k, view) in scene.textures.iter().enumerate() {
        entries.push((11 + k as u32, wgpu::BindingResource::TextureView(view)));
    }
    let bind = bind_group(gpu, &kernel, &entries);
    let mut encoder = device.create_command_encoder(&Default::default());
    {
        let mut pass = encoder.begin_compute_pass(&Default::default());
        pass.set_pipeline(&kernel);
        pass.set_bind_group(0, Some(&bind), &[]);
        pass.dispatch_workgroups((rays.len() as u32).div_ceil(64), 1, 1);
    }
    encoder.copy_buffer_to_buffer(&output, 0, &readback, 0, size);
    gpu.queue.submit([encoder.finish()]);
    let (tx, rx) = mpsc::channel();
    readback.map_async(wgpu::MapMode::Read, .., move |result| {
        let _ = tx.send(result);
    });
    device.poll(wgpu::PollType::wait_indefinitely()).unwrap();
    rx.recv_timeout(Duration::from_secs(120)).unwrap().unwrap();
    let traced =
        bytemuck::cast_slice::<u8, Traced>(&readback.get_mapped_range(..).unwrap()).to_vec();
    readback.unmap();
    traced
}

fn fibonacci(count: usize) -> impl Iterator<Item = Vec3> {
    let golden = std::f32::consts::PI * (3.0 - 5f32.sqrt());
    (0..count).map(move |i| {
        let y = 1.0 - 2.0 * (i as f32 + 0.5) / count as f32;
        let r = (1.0 - y * y).sqrt();
        let phi = golden * i as f32;
        Vec3::new(r * phi.cos(), y, r * phi.sin())
    })
}

fn ray(origin: Vec3, direction: Vec3, mask: u32) -> GpuRay {
    GpuRay {
        origin: origin.into(),
        t_min: 0.0,
        direction: direction.into(),
        t_max: 20.0,
        mask: [mask, 0, 0, 0],
    }
}

/// Clearance of `p` from every box (a lower bound: local distance times the minimum scale).
fn clearance(boxes: &[Box3], p: Vec3) -> f32 {
    boxes
        .iter()
        .map(|b| {
            box_sdf(b.transform.inverse().transform_point3(p))
                * axis_scales(&b.transform).min_element()
        })
        .fold(f32::INFINITY, f32::min)
}

fn validation_scope(gpu: &Gpu) -> wgpu::ErrorScopeGuard {
    gpu.device.push_error_scope(wgpu::ErrorFilter::Validation)
}

fn assert_no_validation_error(scope: wgpu::ErrorScopeGuard) {
    if let Some(error) = pollster::block_on(scope.pop()) {
        panic!("wgpu validation error: {error}");
    }
}

fn close(a: [f32; 4], b: [f32; 4], tolerance: f32) -> bool {
    a.iter().zip(b).all(|(x, y)| (x - y).abs() <= tolerance)
}

fn percentile(values: &mut [f32], p: f32) -> f32 {
    if values.is_empty() {
        return f32::NAN;
    }
    values.sort_by(f32::total_cmp);
    values[((values.len() - 1) as f32 * p).round() as usize]
}

#[test]
fn fixtures_validate_with_ray_query_capability() {
    use naga::valid::{Capabilities, ValidationFlags, Validator};
    for (name, source) in FIXTURES {
        let module = naga::front::wgsl::parse_str(source)
            .unwrap_or_else(|error| panic!("{name}: {}", error.emit_to_string(source)));
        let ray_query = name.contains("ray-query");
        // Every WebGPU device grants pack/unpack2x16float (wgpu derives it from the
        // core downlevel flags), so the baseline models a conformant device.
        let baseline = Capabilities::SHADER_FLOAT16_IN_FLOAT32;
        let capabilities = if ray_query {
            baseline | Capabilities::RAY_QUERY
        } else {
            baseline
        };
        Validator::new(ValidationFlags::all(), capabilities)
            .validate(&module)
            .unwrap_or_else(|error| panic!("{name}: {}", error.emit_to_string(source)));
        if ray_query {
            assert!(
                Validator::new(ValidationFlags::all(), baseline)
                    .validate(&module)
                    .is_err(),
                "{name} must need the Ray Query capability"
            );
        }
    }
}

#[test]
fn hardware_and_global_sdf_traversal_agree_on_one_scene() {
    let Some(gpu) = gpu() else { return };
    let scope = validation_scope(&gpu);
    let scene = build_scene(&gpu, furnished(), &[]);
    let origins = [
        [0.0, 0.0, 0.0],
        [2.0, 1.0, 2.0],
        [-2.4, 2.4, 0.4],
        [-2.0, -1.0, -2.5],
        [2.2, 2.0, -2.0],
        [0.0, 2.5, 0.0],
        [-2.5, -2.3, 2.4],
        [1.5, -0.5, -2.5],
    ]
    .map(Vec3::from);
    for origin in origins {
        assert!(
            clearance(&scene.boxes, origin) > 0.3,
            "origin {origin} must start in free space"
        );
    }
    let rays: Vec<GpuRay> = origins
        .iter()
        .flat_map(|&o| fibonacci(128).map(move |d| ray(o, d, 0xff)))
        .collect();
    let expected: Vec<Expected> = rays
        .iter()
        .map(|r| oracle(&scene.boxes, r).expect("a closed room hits every ray"))
        .collect();
    let hardware = trace(&gpu, &scene, Traversal::RayQuery, &rays);
    let software = trace(&gpu, &scene, Traversal::GlobalSdf, &rays);
    assert_no_validation_error(scope);

    // Ray Query is exact: every ray hits the oracle's instance and face.
    let mut edges = 0;
    for (i, (hit, e)) in hardware.iter().zip(&expected).enumerate() {
        assert_eq!(hit.state[0], STATUS_HIT, "ray {i}: {hit:?}");
        assert_eq!(hit.state[3], e.instance, "ray {i} instance");
        assert!(
            (hit.metrics[0] - e.t).abs() <= 1e-4 * e.t.max(1.0),
            "ray {i}: t {} vs {}",
            hit.metrics[0],
            e.t
        );
        if e.edge {
            edges += 1;
            continue;
        }
        assert!(
            Vec3::from_slice(&hit.normal[..3]).dot(e.normal) > 0.9999,
            "ray {i} normal {:?} vs {}",
            hit.normal,
            e.normal
        );
        assert!(
            close(hit.radiance, card_color(e.card), 1e-5),
            "ray {i} radiance {:?} vs Card {} {:?}",
            hit.radiance,
            e.card,
            card_color(e.card)
        );
    }

    // Global SDF against the same rays. Stated tolerances (voxel = SPACING): every ray
    // hits; the hit point lies within one voxel of the exact surface plane for 95% of
    // rays; |dt| <= 2 voxels for 95% (t error grows as 1/cos at grazing incidence, where
    // the march's surface expansion commits early); Card radiance equals the exact
    // lane for 97% (the rest select a neighbouring face near edges).
    let n = rays.len() as f32;
    let (mut dt, mut plane, mut normal_dot) = (Vec::new(), Vec::new(), Vec::new());
    let (mut hits, mut radiance_match) = (0, 0);
    for (sdf, hw) in software.iter().zip(&hardware) {
        if sdf.state[0] != STATUS_HIT {
            continue;
        }
        hits += 1;
        let exact_normal = Vec3::from_slice(&hw.normal[..3]);
        let offset = Vec3::from_slice(&sdf.position[..3]) - Vec3::from_slice(&hw.position[..3]);
        dt.push((sdf.metrics[0] - hw.metrics[0]).abs());
        plane.push(offset.dot(exact_normal).abs());
        normal_dot.push(Vec3::from_slice(&sdf.normal[..3]).dot(exact_normal));
        radiance_match += usize::from(close(sdf.radiance, hw.radiance, 1e-3));
    }
    let fraction =
        |values: &[f32], limit: f32| values.iter().filter(|&&v| v <= limit).count() as f32 / n;
    let (dt_within, plane_within) = (fraction(&dt, 2.0 * SPACING), fraction(&plane, SPACING));
    let dt_p50 = percentile(&mut dt, 0.5);
    let dt_p95 = percentile(&mut dt, 0.95);
    let plane_p50 = percentile(&mut plane, 0.5);
    let plane_p95 = percentile(&mut plane, 0.95);
    let mean_dot = normal_dot.iter().sum::<f32>() / normal_dot.len().max(1) as f32;
    let dot_p05 = percentile(&mut normal_dot, 0.05);
    let radiance = radiance_match as f32 / n;
    println!(
        "world-traversal parity ({} rays, voxel {SPACING}): ray-query == oracle on all ({edges} edge rays \
         face-ambiguous); global-sdf hit {:.4}; |dt| p50 {dt_p50:.4} p95 {dt_p95:.4}, <=2 voxels {dt_within:.4}; \
         plane distance p50 {plane_p50:.4} p95 {plane_p95:.4}, <=1 voxel {plane_within:.4}; \
         normal dot mean {mean_dot:.4} p05 {dot_p05:.4}; radiance == ray-query {radiance:.4}",
        rays.len(),
        hits as f32 / n,
    );
    assert_eq!(
        hits,
        rays.len(),
        "global-sdf must hit every ray in a closed room"
    );
    assert!(plane_within >= 0.95, "global-sdf plane distance <= 1 voxel");
    assert!(dt_within >= 0.95, "global-sdf |dt| <= 2 voxels");
    assert!(radiance >= 0.97, "global-sdf Card radiance agreement");
}

/// Unlit marker `worldCardRadiance` returns for a hit on a non-resident instance.
const UNLIT: [f32; 4] = [0.0, 0.0, 0.0, -1.0];

/// Card residency on the Ray Query hit path: a committed triangle of an instance whose
/// Cards are pending (installed, not yet captured) reads as unlit (`w = -1`, probe ray
/// status `unlit`), exactly like the Global SDF lane, while resident instances keep
/// their Card radiance. Falsifier: without the residency flag the same hits read black.
#[test]
fn pending_cards_are_unlit_on_ray_query_and_global_sdf() {
    let Some(gpu) = gpu() else { return };
    let scope = validation_scope(&gpu);
    const PENDING: u32 = 200;
    let mut scene = build_scene(&gpu, furnished(), &[PENDING]);
    let origins = [
        [0.0, 0.0, 0.0],
        [2.5, -0.5, -1.5],
        [0.0, -1.5, 2.2],
        [2.6, -2.0, 2.5],
    ]
    .map(Vec3::from);
    for origin in origins {
        assert!(
            clearance(&scene.boxes, origin) > 0.3,
            "origin {origin} must start in free space"
        );
    }
    let rays: Vec<GpuRay> = origins
        .iter()
        .flat_map(|&o| fibonacci(1024).map(move |d| ray(o, d, 0xff)))
        .collect();
    let expected: Vec<Expected> = rays
        .iter()
        .map(|r| oracle(&scene.boxes, r).expect("a closed room hits every ray"))
        .collect();
    let hardware = trace(&gpu, &scene, Traversal::RayQuery, &rays);
    let software = trace(&gpu, &scene, Traversal::GlobalSdf, &rays);
    scene.residency_pending = 0;
    let falsified = trace(&gpu, &scene, Traversal::RayQuery, &rays);
    assert_no_validation_error(scope);

    let (mut pending, mut resident, mut sdf_unlit) = (0, 0, 0);
    for (i, (hit, e)) in hardware.iter().zip(&expected).enumerate() {
        assert_eq!(hit.state[0], STATUS_HIT, "ray {i}: {hit:?}");
        assert_eq!(hit.state[3], e.instance, "ray {i} instance");
        if e.instance == PENDING {
            pending += 1;
            assert_eq!(hit.radiance, UNLIT, "ray {i}: a pending instance is unlit");
            assert_eq!(
                falsified[i].radiance, [0.0; 4],
                "ray {i}: without residency the pending hit reads black"
            );
            sdf_unlit += usize::from(software[i].radiance == UNLIT);
        } else if !e.edge {
            resident += 1;
            assert!(
                close(hit.radiance, card_color(e.card), 1e-5),
                "ray {i}: a resident instance keeps its Card radiance {:?}",
                hit.radiance
            );
        }
    }
    let sdf_agreement = sdf_unlit as f32 / pending.max(1) as f32;
    println!(
        "card residency ({} rays): ray-query pending hits {pending} all unlit, \
         resident hits {resident} lit; global-sdf unlit on {sdf_agreement:.4} of pending hits",
        rays.len()
    );
    assert!(
        pending > 50,
        "the pending instance must be reached by many rays"
    );
    assert!(
        resident > 500,
        "resident instances must be reached by many rays"
    );
    // Distance association near the floor contact can pick the floor's Cards.
    assert!(
        sdf_agreement >= 0.9,
        "global-sdf reads the same pending hits as unlit"
    );
}

#[test]
fn thin_wall_does_not_leak_through_ray_query() {
    let Some(gpu) = gpu() else { return };
    let scope = validation_scope(&gpu);
    let mut rays = Vec::new();
    for y in [-2.0, -0.7, 0.7, 2.0] {
        for z in [-2.0, -0.7, 0.7, 2.0] {
            let origin = Vec3::new(-1.5, y, z);
            rays.extend(
                fibonacci(96)
                    .filter(|d| d.x > 0.25)
                    .map(|d| ray(origin, d, 0x01)),
            );
        }
    }
    // A leak misses or lands past the plate. Admitted rays reference-hit the plate, and
    // without it would land past that line, so a removed plate must leak every one.
    let past = PLATE_X + 0.5 * PLATE_THICKNESS + SPACING;
    let (reference, removed) = (partitioned(0x01), partitioned(0x02));
    let plate_bound: Vec<bool> = rays
        .iter()
        .map(|r| {
            oracle(&reference, r).is_some_and(|e| e.instance == PLATE_ID)
                && oracle(&removed, r).is_some_and(|e| r.origin[0] + r.direction[0] * e.t > past)
        })
        .collect();
    let bound = plate_bound.iter().filter(|&&b| b).count();
    let leaks = |traced: &[Traced]| {
        traced
            .iter()
            .zip(&plate_bound)
            .filter(|(hit, &b)| b && (hit.state[0] != STATUS_HIT || hit.position[0] > past))
            .count()
    };
    let visible = build_scene(&gpu, partitioned(0x01), &[]);
    let hardware = trace(&gpu, &visible, Traversal::RayQuery, &rays);
    let software = trace(&gpu, &visible, Traversal::GlobalSdf, &rays);
    let (hardware_leaks, software_leaks) = (leaks(&hardware), leaks(&software));
    // Falsifier: the same detector must see every ray leak once the plate is masked out.
    let masked = build_scene(&gpu, partitioned(0x02), &[]);
    let falsified = trace(&gpu, &masked, Traversal::RayQuery, &rays);
    let masked_leaks = leaks(&falsified);
    assert_no_validation_error(scope);
    println!(
        "thin wall ({PLATE_THICKNESS} thick, voxel {SPACING}): {bound} plate-bound rays; \
         ray-query leaks {hardware_leaks}, global-sdf leaks {software_leaks}, \
         masked-plate falsifier leaks {masked_leaks}"
    );
    assert!(bound > 100, "the plate must be reached by many rays");
    assert_eq!(hardware_leaks, 0, "ray-query must not cross the thin wall");
    assert_eq!(
        masked_leaks, bound,
        "the leak detector must see a removed wall"
    );
}
