import { resolve } from 'node:path';
import type { RuntimeAssetBinding } from '@forgeax/engine-types';

export const VIRTUAL_PACK_RUNTIME_ID = 'virtual:forgeax/pack-runtime';
export const SCOPED_RUNTIME_PREFIX = '\0forgeax:gallery-pack-runtime:';
export const GALLERY_UNBOUND_SCOPE = '__gallery_unbound__';

const activeBindings = new Map<string, RuntimeAssetBinding>();

export function scopedRuntimeId(scopeId: string): string {
  return `${SCOPED_RUNTIME_PREFIX}${scopeId}`;
}

export function assetRuntimeConfigModulePath(appsDir: string): string {
  return resolve(appsDir, 'shared/src/asset-runtime-config.ts');
}

export function scopeFromRuntimeId(id: string): string | undefined {
  if (!id.startsWith(SCOPED_RUNTIME_PREFIX)) return undefined;
  return id.slice(SCOPED_RUNTIME_PREFIX.length);
}

export function isGalleryPackRuntimeId(id: string): boolean {
  return scopeFromRuntimeId(id) !== undefined;
}

export function rememberActiveBinding(binding: RuntimeAssetBinding | undefined): void {
  if (binding === undefined) return;
  activeBindings.set(binding.scopeId, binding);
}

export function bindingForScope(scopeId: string): RuntimeAssetBinding | undefined {
  return activeBindings.get(scopeId);
}

export function emitGalleryPackRuntimeModule(binding: RuntimeAssetBinding | undefined): string {
  if (binding === undefined) {
    return [
      '// AUTO-GENERATED by forgeax demo-gallery scoped pack runtime.',
      'export const runtimeBinding = undefined;',
      'export function createRuntimeAssetImportTransport() { return undefined; }',
    ].join('\n');
  }

  const serialized = JSON.stringify(binding);
  return [
    '// AUTO-GENERATED by forgeax demo-gallery scoped pack runtime.',
    "import { createDevImportTransport } from '@forgeax/engine-runtime';",
    `export const runtimeBinding = ${serialized};`,
    'export function createRuntimeAssetImportTransport(importBinding = runtimeBinding) {',
    '  return importBinding === undefined ? undefined : createDevImportTransport(importBinding);',
    '}',
  ].join('\n');
}
