// @forgeax/engine-vite-plugin-pack — Vite plugin for the forgeax engine asset package system.
//
// Two modes:
//   configureServer(server) — dev mode: scan(roots), expose /__pack/lookup/:guid +
//     /__pack/index routes via server.middlewares.use, watch
//     sidecar and source-file changes with
//     node:fs.watch and emit `server.ws.send({ type: 'full-reload' })`
//     to broadcast HMR full-page reloads (AC-11).
//   generateBundle(this) — build mode: scan(roots) → import each `kind: 'texture'`
//     entry (parseImage on the source JPG, emitFile the raw RGBA bytes as a
//     hashed asset, rewrite `relativeUrl` to the hashed path) →
//     emitFile('pack-index.json', ...).
//
// fs.watch instead of chokidar rationale:
//   M4 does not introduce new npm runtime dependencies. node:fs.watch is sufficient
//   for dev HMR when pack file counts are <= 1000 (R-3 performance assumption).
//   fs.watch trigger latency < 100ms for typical pack file tree sizes.
//   chokidar provides recursive watch on Linux (where fs.watch is non-recursive)
//   but pack files are only generated by the build pipeline, not edited by human
//   users at sub-second rates — polling-style invalidation on next request is
//   also acceptable as a fallback.

import { watch as fsWatch, readFileSync } from 'node:fs';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import {
  IMPORT_ERROR_HINTS,
  ImportError,
  ImporterRegistry,
  type ImportRunnerFs,
  type RunImportMeta,
  runImport,
} from '@forgeax/engine-import';
import { loadAssetConfig } from '@forgeax/engine-pack/config';
import { resolveAssetSource } from '@forgeax/engine-pack/resolve';
import { scan } from '@forgeax/engine-pack/scanner';
import type { ImageMetadata, Importer, PackIndexEntry } from '@forgeax/engine-types';
import { createUiImporter } from '@forgeax/engine-ui/importer';
import { buildCatalog } from './build-catalog.js';
import { compressArtifact } from './compress-artifact.js';
import {
  productAssetByGuid,
  productAssetsByGuid,
  projectUiBuildArtifacts,
} from './import-products.js';
import { importTextureEntry } from './import-texture.js';
import {
  loadSharedPackInput,
  projectPackIndexUrl,
  projectSharedPackCatalog,
  resolvePackBuildInputs,
} from './shared-build-inputs.js';
import { dedupeFinalizedUiEntries, finalizeUiArtifact } from './ui-artifact-finalizer.js';

// ─── Types ──────────────────────────────────────────────────────────────────

// PackIndexEntry now lives in @forgeax/engine-types (feat-20260517 D-2 SSOT).
// Re-export so existing consumers (tests, downstream packages) keep their
// `import { PackIndexEntry } from '@forgeax/engine-vite-plugin-pack'` paths
// working without a same-PR API break.
export type { PackIndexEntry };

// Minimal structural interface for Vite Plugin (duck-typed; no vite import needed).
//
// `emitFile` covers two Rollup variants we use here:
//   - text asset:  `{ type: 'asset', fileName: 'pack-index.json', source: '...' }`
//     -> emitted at the explicit path with no hash (used for the catalog index).
//   - binary asset: `{ type: 'asset', name: '<guid>', source: <Uint8Array>,
//     originalFileName: <abs-jpg-path> }` -> Rollup picks
//     `assets/[name]-[hash][extname]` by default (D-2). We capture the
//     returned `referenceId` and resolve the hashed filename via
//     `getFileName(referenceId)` once Rollup has finished name resolution
//     (research F1+F3).
interface MinimalPluginContext {
  emitFile(asset: {
    type: 'asset';
    fileName?: string;
    name?: string;
    originalFileName?: string;
    source: string | Uint8Array;
  }): string;
  getFileName(referenceId: string): string;
}

type NextHandleFunction = (err?: unknown) => void;

interface ServerResponseLike {
  statusCode: number;
  setHeader(name: string, value: string): void;
  end(chunk: string | Uint8Array): void;
}

interface IncomingMessageLike {
  readonly url?: string | undefined;
}

type ConnectMiddleware = (
  req: IncomingMessageLike,
  res: ServerResponseLike,
  next: NextHandleFunction,
) => void | Promise<void>;

interface MiddlewaresLike {
  use(handler: ConnectMiddleware): unknown;
}

interface WatcherLike {
  on(event: string, cb: (...args: unknown[]) => void): unknown;
}

interface ViteDevServerLike {
  readonly middlewares: MiddlewaresLike;
  readonly watcher?: WatcherLike | undefined;
  readonly ws?: WsLike | undefined;
}

interface WsLike {
  send(payload: { type: string } & Record<string, unknown>): void;
}

/**
 * Vite HMR custom-event name the dev server pushes when a watched asset file
 * (sidecar or image/glTF source) changes. A tooling subscriber receives it via
 * `import.meta.hot.on(ASSET_CHANGED_EVENT, (data: AssetChangedPayload) => ...)`
 * and re-queries `/__pack/index` -- replacing filesystem polling with a push
 * from the catalog-owner. Distinct from the `full-reload` the running game
 * still receives; this channel is for editors/inspectors, not the game.
 */
export const ASSET_CHANGED_EVENT = 'forgeax:asset-changed';

/** Payload carried by {@link ASSET_CHANGED_EVENT}. */
export interface AssetChangedPayload {
  /** Watched file path (relative to a scanned root) that changed. */
  readonly file: string;
  /** node:fs.watch event kind (`'rename'` | `'change'`). */
  readonly event: string;
  /**
   * Which watch class fired: `'sidecar'` (`.meta.json` / `.pack.json` -- the
   * catalog was rebuilt) or `'source'` (image / glTF bytes -- catalog rows are
   * unchanged, only pixels). A subscriber re-queries the catalog only for
   * `'sidecar'`.
   */
  readonly kind: 'sidecar' | 'source';
}

/**
 * Push {@link ASSET_CHANGED_EVENT} over the Vite HMR socket. No-op when no ws
 * channel is wired (graceful degradation, architecture-principles §9).
 */
function emitAssetChanged(
  server: ViteDevServerLike,
  file: string,
  event: string,
  kind: 'sidecar' | 'source',
): void {
  const data: AssetChangedPayload = { file, event, kind };
  server.ws?.send({ type: 'custom', event: ASSET_CHANGED_EVENT, data });
}

/** Shape of the plugin returned by pluginPack(). */
export interface ForgeaXPackPlugin {
  readonly name: string;
  configureServer(server: ViteDevServerLike): void;
  generateBundle(this: MinimalPluginContext): Promise<void>;
}

// ─── Options ────────────────────────────────────────────────────────────────

export interface PluginPackOptions {
  /**
   * Root directories to scan for .meta.json / .pack.json files.
   * Defaults to ["assets/"] relative to cwd; reads from root
   * package.json#forgeax.assets.roots[] when present.
   */
  readonly roots?: readonly string[] | undefined;
  /**
   * Vite `base` the engine is hosted under (e.g. `'/preview/'` when
   * forgeax-studio mounts the engine behind its `/preview/*` proxy).
   * Prefixed onto every catalog `relativeUrl` so the runtime's verbatim
   * `fetch(relativeUrl)` from the page origin reaches the engine instead of
   * the host SPA (which would return index.html → `asset-fetch-failed`).
   * Defaults to `'/'` (engine's own apps at vite root) — a no-op prefix.
   */
  readonly base?: string | undefined;
  /**
   * M4 / w32 (AC-20): registered `Importer` instances the lazy-import
   * HTTP adapter (`POST /__import/:guid`) dispatches on `meta.importer`.
   * Each importer must carry a non-empty `key` + a `import` function.
   * When `undefined` or `[]`, the `POST /__import/:guid` route is not
   * mounted (dev-only lazy import is disabled).
   */
  readonly importers?: readonly Importer[] | undefined;
}

// ─── Config loading ──────────────────────────────────────────────────────────

// ─── Catalog builder ────────────────────────────────────────────────────────
// buildCatalog is extracted into ./build-catalog.ts so its 2 arms
// (`.pack.json` legacy + `.meta.json` image) stay reviewable in one
// file (feat-20260517 M1 w3). The factory below imports it for both the
// dev-mode middleware and the build-mode generateBundle hook.

// ─── Mime sniff ─────────────────────────────────────────────────────────────

function mimeFromPath(path: string): 'image/jpeg' | 'image/png' | undefined {
  const lower = path.toLowerCase();
  if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'image/jpeg';
  if (lower.endsWith('.png')) return 'image/png';
  return undefined;
}

// Dev import DDC (Derived Data Cache) location. The imported `.bin` is derived
// data -- delete it and the next `loadByGuid` re-derives it from the source.
// Keying it by GUID under `node_modules/.cache/forgeax-ddc/` keeps it gitignored
// everywhere (root `node_modules/` rule) so it never pollutes the source tree,
// which for vendor assets (e.g. Sponza textures) is a tracked git submodule.
// Deterministic from `(cwd, guid)`: the write site (importOneTexture) and the
// warm-refresh reconstruction site (buildUrlToAbs) MUST agree on this formula.
// GUIDs are globally unique (UUIDv5/v7 per sub-asset), so no collision with the
// build arm's `dist/assets/<guid>-<hash>.bin` Rollup namespace.
function ddcPath(cwd: string, guidLower: string): string {
  return resolve(cwd, 'node_modules/.cache/forgeax-ddc', `${guidLower}.bin`);
}

/**
 * AC-01: read an explicit per-asset compression override from a meta sidecar's
 * `importSettings.compression`. Returns the narrowed union value, or undefined
 * when absent / malformed (falls back to the kind-keyed default table).
 */
function readCompressionOverride(importSettings: unknown): 'none' | 'zstd' | undefined {
  if (importSettings === null || typeof importSettings !== 'object') return undefined;
  const c = (importSettings as { compression?: unknown }).compression;
  return c === 'none' || c === 'zstd' ? c : undefined;
}

/**
 * AC-01: read the explicit compression override from a meta sidecar path (used
 * by the texture arms, which reach compression via `importTextureEntry` and do
 * not otherwise parse the meta). Returns undefined when the path is unknown /
 * unreadable / has no override.
 */
async function readOverrideFromMeta(
  metaPath: string | undefined,
): Promise<'none' | 'zstd' | undefined> {
  if (metaPath === undefined) return undefined;
  try {
    const meta = JSON.parse(await readFile(metaPath, 'utf-8')) as { importSettings?: unknown };
    return readCompressionOverride(meta.importSettings);
  } catch {
    return undefined;
  }
}

function buildUrlToAbs(entries: PackIndexEntry[]): Map<string, string> {
  const cwd = process.cwd();
  const map = new Map<string, string>();
  for (const entry of entries) {
    // An imported row's `relativeUrl` ends with `.${guid}.bin` (the runtime
    // textureLoader keys on the `.bin` suffix) while its `sourcePath` is
    // preserved as the original source (build-mode parity, so
    // `sourcePath.endsWith(uri)` reverse-lookups keep working on a warm
    // refresh). The imported bytes live in the DDC, NOT next to the source, so
    // reconstruct the abs path via `ddcPath` -- resolving `sourcePath` would
    // serve the raw source bytes for the `.bin` URL after a watch-triggered
    // catalog rebuild rebuilds this map.
    const isImportedBin = entry.relativeUrl.endsWith(`.${entry.guid.toLowerCase()}.bin`);
    const abs = isImportedBin
      ? ddcPath(cwd, entry.guid.toLowerCase())
      : resolve(cwd, entry.sourcePath);
    map.set(entry.relativeUrl, abs);
  }
  return map;
}

/**
 * M4 / w32 (AC-20): scan roots for `*.meta.json` sidecars and build a
 * `GUID -> absolute-meta-path` index so `POST /__import/:guid` can find the
 * declaring sidecar without re-scanning.
 */
async function buildGuidToMetaMap(roots: readonly string[]): Promise<Map<string, string>> {
  const map = new Map<string, string>();
  for (const root of roots) {
    const scanResult = await scan([root]);
    if (!scanResult.ok) continue;
    const metaPaths = scanResult.value.filter((p) => p.endsWith('.meta.json'));
    for (const metaPath of metaPaths) {
      try {
        const content = await readFile(metaPath, 'utf-8');
        const meta = JSON.parse(content) as {
          subAssets?: ReadonlyArray<{ guid: string }>;
        };
        if (meta.subAssets !== undefined) {
          for (const sub of meta.subAssets) {
            map.set(sub.guid.toLowerCase(), metaPath);
          }
        }
      } catch {
        // Skip unreadable meta files
      }
    }
  }
  return map;
}

// ─── Main factory ───────────────────────────────────────────────────────────

/**
 * Vite plugin factory for the forgeax engine asset package system.
 *
 * Dev mode responsibilities:
 * - configureServer: scan roots on startup, expose /__pack/index and
 *   /__pack/lookup/:guid HTTP routes via server.middlewares.use.
 * - Watch .meta.json / .pack.json files via node:fs.watch (no chokidar dep).
 *   On change, rebuild the catalog so the next /__pack request reflects the
 *   new state. Also attempts HMR invalidation via server.watcher events.
 *
 * Build mode responsibilities:
 * - generateBundle: scan roots, import each `kind: 'texture'` row
 *   (parseImage on the source JPG, emitFile the RGBA bytes as a hashed
 *   binary asset, rewrite `relativeUrl` to the hashed `<guid>-[hash].bin`
 *   path), then emit pack-index.json as a Rollup asset.
 *
 * @example
 * ```ts
 * // vite.config.ts
 * import { pluginPack } from '@forgeax/engine-vite-plugin-pack';
 * export default { plugins: [pluginPack()] };
 * ```
 */
export function pluginPack(opts: PluginPackOptions = {}): ForgeaXPackPlugin {
  // Mutable catalog state — rebuilt on startup and on file watch events.
  let catalog: PackIndexEntry[] = [];
  // Map from normalized `relativeUrl` to absolute source path for serving
  // files that live outside the Vite root (e.g. submodule assets).
  let urlToAbs: Map<string, string> = new Map();
  let catalogReady = false;

  // M4 / w32 (AC-20): GUID -> meta-path index built alongside the catalog so
  // `POST /__import/:guid` can find the declaring meta sidecar. Rebuilt on
  // every catalog rebuild (startup + watch events).
  let guidToMeta: Map<string, string> = new Map();

  // Per-asset import overlay (the four-verb redesign, 2026-06-06). A dev import
  // produces ONE imported `.bin` row and records it here keyed by lowercased
  // GUID. Every catalog (re)build overlays these rows over the freshly scanned
  // raw rows so an imported row is NEVER reset back to its raw source -- import
  // is monotonic and idempotent. This replaces #300's whole-catalog rebuild +
  // swap in `POST /__import`, which raced under concurrent load (122 Sponza
  // textures each swapping a freshly-rebuilt catalog that knew only its own
  // `.bin`, so every other texture's imported row was reset to raw and import
  // never converged).
  const importedRows: Map<string, PackIndexEntry> = new Map();

  // In-flight import coalescing: two concurrent `loadByGuid` calls for the same
  // texture share a single import promise (per-asset idempotency at the verb
  // boundary -- `import(guid)` is the unit, not "rebuild the world").
  const inFlightImports: Map<string, Promise<PackIndexEntry[]>> = new Map();

  // M4 / w20 (D-2): per-meta import coalescing. Two concurrent `loadByGuid`
  // calls hitting the same meta sidecar share a single `runImport` pass.
  // Keyed by absolute metaPath; the promise resolves to the full set of
  // PackIndexEntry rows produced by that meta's import. On completion the
  // entry is deleted so a subsequent sidecar-triggered rebuild can re-import.
  // This reduces the 122-concurrent-Sponza-texture case from 122 decodes to
  // 1 decode (per meta), matching the build-mode `generateBundle` single-pass
  // behaviour (requirements AC-15).
  const inFlightMetaImports: Map<string, Promise<PackIndexEntry[]>> = new Map();

  // bug-20260610-dev-meta-pack-not-served: in-memory store for `.pack.json`
  // bodies produced by `startMetaImport`. Keys are dev URLs of the form
  // `/__forgeax-ddc/<firstGuid>.pack.json`; values are the serialised pack
  // JSON. Mesh / scene / material sub-asset rows whose payloads live inside
  // the pack (no separate `.bin`) get their `relativeUrl` rewritten to this
  // URL so the runtime's `fetchPackFile` reaches a body that has `assets[]`,
  // matching the build-mode `generateBundle` behaviour where every sub-asset
  // row points at a hashed `.pack.json` Rollup asset (lines ~1000-1024).
  // Without this map the dev path returned the raw `.gltf` URL for non-binary
  // sub-assets, the runtime fetched the gltf JSON (200 OK), `assets[]` was
  // undefined, and `loadByGuid` failed `asset-not-found` on the first scene /
  // mesh / material lookup.
  const metaPackBodies: Map<string, string> = new Map();
  const uiArtifactBodies: Map<string, { readonly bytes: Uint8Array; readonly mimeType: string }> =
    new Map();
  const DEV_PACK_PREFIX = '/__forgeax-ddc/';

  // Overlay the persistent imported rows over a freshly scanned raw catalog,
  // de-duplicating any stale raw row for a GUID that has been imported (so the
  // imported `.bin` row uniquely wins, e.g. a legacy `.pack.json` duplicate).
  function applyImportedRows(raw: readonly PackIndexEntry[]): PackIndexEntry[] {
    if (importedRows.size === 0) return raw.slice();
    const seen = new Set<string>();
    const out: PackIndexEntry[] = [];
    for (const e of raw) {
      const key = e.guid.toLowerCase();
      const imported = importedRows.get(key);
      if (imported !== undefined) {
        if (!seen.has(key)) {
          out.push(imported);
          seen.add(key);
        }
        continue;
      }
      out.push(e);
    }
    return out;
  }

  // Import exactly ONE texture GUID to the DDC
  // (`node_modules/.cache/forgeax-ddc/<guid>.bin`, see ddcPath -- gitignored,
  // never written into the source tree) and incrementally patch the
  // live catalog + urlToAbs for that single row. No whole-catalog rebuild, no
  // global swap. Idempotent: a GUID already in the import overlay returns its
  // imported row without re-importing. Returns `[]` when the GUID is absent from
  // the catalog or its row is not an importable texture (the caller fails fast
  // rather than silently rebuilding).
  async function importOneTexture(guidLower: string): Promise<PackIndexEntry[]> {
    const already = importedRows.get(guidLower);
    if (already !== undefined) return [already];
    const raw = catalog.find((e) => e.guid.toLowerCase() === guidLower);
    if (raw === undefined) return [];
    const imported = await importTextureEntry(raw, { cwd: process.cwd() });
    if ('skipped' in imported) {
      // Fail-fast (architecture-principles §5), mirroring the per-meta path's
      // `throw runResult.error`: a REAL cook failure (source read / decode /
      // no-produced) must surface a structured ImportError so the POST route
      // reports `.code` + `detail.reason` in the 422 body and the browser
      // console -- not collapse to `[]` -> a generic "could not be imported".
      // A BENIGN skip (non-texture kind / unknown extension) is not an error:
      // return `[]` so the route 422s with the generic "not an importable
      // texture" hint (the build arm passes the raw row through; the dev route
      // has no raw-row fallback, so `[]` is the benign signal here).
      if (imported.real) {
        throw new ImportError({
          code: 'import-internal-error',
          expected: `an importable texture source for guid ${raw.guid}`,
          hint: IMPORT_ERROR_HINTS['import-internal-error'],
          detail: { reason: imported.skipped },
        });
      }
      return [];
    }
    const suffix = `.${guidLower}.bin`;
    const binAbs = ddcPath(process.cwd(), guidLower);
    await mkdir(dirname(binAbs), { recursive: true });
    // (A) Texture arm dev: compress after importTextureEntry, before writeFile (D-3).
    // M2 default 'none' → pass-through; M3 flips to 'zstd' in STRATEGY_TABLE.
    // AC-01: honor an explicit importSettings.compression override from the meta.
    const texOverride = await readOverrideFromMeta(guidToMeta.get(guidLower));
    const compressed = await compressArtifact({
      bytes: imported.bytes,
      kind: 'texture',
      isPackJson: false,
      ...(texOverride !== undefined ? { override: texOverride } : {}),
      // Carry the importer's resolved delivery encoding so a Basis KTX2 row
      // records its basis-* discriminant (loader transcode dispatch) instead of
      // the STRATEGY_TABLE 'none' default (which fell through to a scheme=1 KTX2
      // reject). Dev path parity with the build arm.
      ...(imported.metadata.compression !== undefined
        ? { alreadyCompressed: imported.metadata.compression }
        : {}),
    });
    await writeFile(binAbs, compressed.compressed);
    const importedRow: PackIndexEntry = {
      guid: raw.guid,
      relativeUrl: `${raw.relativeUrl}${suffix}`,
      kind: raw.kind,
      // Preserve the ORIGINAL source path (the `.jpg`/`.png`/`.hdr`), matching
      // the build-mode `generateBundle` import which keeps `sourcePath:
      // entry.sourcePath` and only rewrites `relativeUrl` to the imported `.bin`.
      // Consumers reverse-map a glTF texture URI to its GUID via
      // `sourcePath.endsWith(uri)` (e.g. learn-render 3.1 model-loading's
      // findTextureGuidByFilename); overwriting `sourcePath` with the `.bin`
      // path broke that lookup on a warm refresh -- the row was discoverable on
      // cold load (raw `.jpg` sourcePath) but invisible after the import
      // overwrote it, so every texture silently dropped on the second load. The
      // imported bytes live in the DDC (binAbs), keyed into urlToAbs below by the
      // `.bin` relativeUrl.
      sourcePath: raw.sourcePath,
      metadata: imported.metadata,
      compression: compressed.compression,
    };
    importedRows.set(guidLower, importedRow);
    const idx = catalog.findIndex((e) => e.guid.toLowerCase() === guidLower);
    if (idx >= 0) catalog[idx] = importedRow;
    urlToAbs.set(importedRow.relativeUrl, binAbs);
    return [importedRow];
  }

  // M4 / w20 (D-2): per-meta import. Called once per metaPath, runs the
  // import runner on the whole sidecar, writes imported .bin entries to the
  // DDC, overlays all produced rows onto the catalog, and returns the
  // resulting PackIndexEntry[] for all rows belonging to this meta.
  async function startMetaImport(metaPath: string): Promise<PackIndexEntry[]> {
    const cwd = process.cwd();
    const { paths } = loadAssetConfig(cwd);
    let rm: unknown;
    try {
      rm = JSON.parse(await readFile(metaPath, 'utf-8'));
    } catch {
      throw new ImportError({
        code: 'import-internal-error',
        expected: `parseable JSON meta sidecar at ${metaPath}`,
        hint: IMPORT_ERROR_HINTS['import-internal-error'],
        detail: { reason: `failed to read or parse meta sidecar: ${metaPath}` },
      });
    }
    const meta = rm as {
      importer: string;
      source?: string;
      importSettings?: unknown;
      subAssets: ReadonlyArray<{ guid: string; sourceIndex: number; kind: string }>;
    };

    // AC-01: explicit per-asset compression override declared in importSettings.
    const metaOverride = readCompressionOverride(meta.importSettings);

    const sourceResult = resolveAssetSource(metaPath, meta.source, paths);
    if (!sourceResult.ok) {
      throw new ImportError({
        code: 'import-internal-error',
        expected: `resolvable source in meta sidecar at ${metaPath}`,
        hint: sourceResult.error.hint,
        detail: { reason: `source resolution failed: ${sourceResult.error.code}` },
      });
    }

    const runMeta: RunImportMeta = {
      importer: meta.importer,
      source: sourceResult.value,
      subAssets: meta.subAssets,
    };
    if (meta.importSettings !== undefined) {
      (runMeta as { importSettings?: Readonly<Record<string, unknown>> }).importSettings =
        meta.importSettings as Readonly<Record<string, unknown>>;
    }

    const runResult = await runImport(runMeta, importerRegistry, fsForImport);
    // Fail-fast (architecture-principles §5): a failed import must not collapse
    // to an empty result that the route can only report as a generic
    // `import-failed`. Throw the structured ImportError so the dev route can
    // surface `.code` + `detail.reason` (e.g. `fbx-mesh-type-unsupported` ->
    // "convert NURBS to polygon mesh") in the 422 body and the browser console, instead of the
    // opaque `asset-not-imported` the runtime otherwise reports.
    if (!runResult.ok) throw runResult.error;
    if ('skipped' in runResult.value) return [];

    if (meta.importer === 'ui') {
      const guid = meta.subAssets[0]?.guid;
      if (guid === undefined) return [];
      const finalized = finalizeUiArtifact(runResult.value.product as never, {
        artifactUrl: (artifact) => `/__ui/${guid}/${artifact.path}`,
      });
      if (!finalized.ok)
        throw new ImportError({
          code: 'import-internal-error',
          expected: finalized.error.expected,
          hint: finalized.error.hint,
          detail: { reason: finalized.error.detail.token ?? finalized.error.code },
        });
      const htmlUrl = `/__ui/${guid}/index.html`;
      uiArtifactBodies.set(htmlUrl, {
        bytes: new TextEncoder().encode(finalized.value.asset.html),
        mimeType: 'text/html',
      });
      uiArtifactBodies.set(`/__ui/${guid}/style.css`, {
        bytes: new TextEncoder().encode(finalized.value.asset.css),
        mimeType: 'text/css',
      });
      for (const artifact of runResult.value.product.artifacts) {
        uiArtifactBodies.set(`/__ui/${guid}/${artifact.path}`, {
          bytes: artifact.bytes,
          mimeType: artifact.mimeType,
        });
      }
      const uiRow = catalog.find((entry) => entry.guid.toLowerCase() === guid.toLowerCase());
      if (uiRow !== undefined) {
        // Runtime pack loading expects a JSON DDC body containing the typed
        // asset payload. Keep the finalized HTML/CSS artifact routes for
        // referenced resources, but point the catalog row at a dev pack body
        // so loadByGuid can parse and register the UiAsset itself.
        const packUrl = `${DEV_PACK_PREFIX}${guid.toLowerCase()}.pack.json`;
        metaPackBodies.set(
          packUrl,
          JSON.stringify({
            schemaVersion: '1.0.0',
            kind: 'internal-text-package',
            assets: [{ guid, kind: 'ui', payload: finalized.value.asset, refs: [] }],
          }),
        );
        const updated = { ...uiRow, relativeUrl: packUrl };
        importedRows.set(guid.toLowerCase(), updated);
        const index = catalog.findIndex((entry) => entry.guid.toLowerCase() === guid.toLowerCase());
        if (index >= 0) catalog[index] = updated;
        return [updated];
      }
      return [];
    }

    const { pack, bins } = runResult.value;
    const allEntries: PackIndexEntry[] = [];

    // bug-20260610-dev-meta-pack-not-served: serialise the produced pack JSON
    // ONCE and register it under a deterministic dev URL. Non-binary
    // sub-assets (mesh / scene / material) whose payloads live inside this
    // pack body get their `relativeUrl` rewritten to point here, matching the
    // build-mode behaviour where every sub-asset row points at a hashed
    // `.pack.json` Rollup asset.
    const firstSubGuid = meta.subAssets[0]?.guid?.toLowerCase();
    const packUrl =
      firstSubGuid !== undefined ? `${DEV_PACK_PREFIX}${firstSubGuid}.pack.json` : undefined;
    if (packUrl !== undefined) {
      metaPackBodies.set(packUrl, JSON.stringify(pack));
    }

    // For each sub-asset declared in the meta, look up its catalog row
    // and overlay the imported form.
    for (const sub of meta.subAssets) {
      const guidLower = sub.guid.toLowerCase();
      const raw = catalog.find((e) => e.guid.toLowerCase() === guidLower);
      if (raw === undefined) continue;

      // If this sub-asset has binary data in bins, write it to the DDC
      // and rewrite the row to a .bin relativeUrl.
      const bytes = bins?.get(guidLower);
      if (bytes !== undefined) {
        const binAbs = ddcPath(cwd, guidLower);
        await mkdir(dirname(binAbs), { recursive: true });
        // (C) Mesh bins arm dev: compress after bins.get, before writeFile (D-3).
        const compressKind = raw.kind === 'mesh' ? 'mesh' : 'texture';
        const compressedBin = await compressArtifact({
          bytes,
          kind: compressKind,
          isPackJson: false,
          ...(metaOverride !== undefined ? { override: metaOverride } : {}),
        });
        await writeFile(binAbs, compressedBin.compressed);
        const suffix = `.${guidLower}.bin`;
        // round-2 finding 4: overlay metadata.colorSpace / format / mipmap
        // from the imported TextureAsset payload so dev pack-index reflects
        // per-image truth (catalog default 'linear' is wrong for srgb
        // baseColors). Mirrors the generateBundle build-mode arm.
        const importedAsset = productAssetByGuid(runResult.value.product, guidLower);
        const importedPayload = importedAsset?.payload as
          | {
              colorSpace?: 'srgb' | 'linear';
              format?: GPUTextureFormat;
              mipmap?: boolean;
              width?: number;
              height?: number;
            }
          | undefined;
        let overlaidMetadata: ImageMetadata | undefined;
        if (raw.metadata?.kind === 'texture') {
          overlaidMetadata = {
            kind: 'texture',
            format: importedPayload?.format ?? raw.metadata.format,
            colorSpace: importedPayload?.colorSpace ?? raw.metadata.colorSpace,
            mipmap: importedPayload?.mipmap ?? raw.metadata.mipmap,
            ...(importedPayload?.width !== undefined ? { width: importedPayload.width } : {}),
            ...(importedPayload?.height !== undefined ? { height: importedPayload.height } : {}),
          };
        }
        const importedRow: PackIndexEntry = {
          guid: raw.guid,
          relativeUrl: `${raw.relativeUrl}${suffix}`,
          kind: raw.kind,
          sourcePath: raw.sourcePath,
          // Carry the raw catalog row's derived display name (buildCatalog ->
          // deriveAssetName: source basename for GLB sub-assets) into the
          // imported row. Rebuilding the row field-by-field dropped it, so a
          // lazy-cooked GLB's sub-assets showed blank in the Content Browser
          // while the un-cooked /pack-index.json still had the name.
          ...(raw.name !== undefined ? { name: raw.name } : {}),
          ...(overlaidMetadata !== undefined
            ? { metadata: overlaidMetadata }
            : raw.metadata !== undefined
              ? { metadata: raw.metadata }
              : {}),
          // Carry the DDC's outgoing dependency edges into the catalog row so
          // the Content Browser dependency graph sees them without re-fetching
          // the .pack.json body (feat: listCatalog refs).
          ...(importedAsset?.refs !== undefined
            ? { refs: importedAsset.refs.map((ref) => ref.guid) }
            : {}),
          compression: compressedBin.compression,
        };
        importedRows.set(guidLower, importedRow);
        const idx = catalog.findIndex((e) => e.guid.toLowerCase() === guidLower);
        if (idx >= 0) catalog[idx] = importedRow;
        urlToAbs.set(importedRow.relativeUrl, binAbs);
        allEntries.push(importedRow);
      } else {
        // Non-binary sub-assets (mesh / material / scene): the payload lives
        // inside the in-memory pack body. Point `relativeUrl` at the dev pack
        // URL so the runtime's `fetchPackFile` reaches a body containing
        // `assets[]` (mirroring the build-mode hashed `.pack.json` rewrite at
        // generateBundle:~1000-1024). Keeping `raw` here was the
        // bug-20260610 root cause — runtime fetched the raw `.gltf` JSON,
        // found no `assets[]`, returned `asset-not-found`.
        // Carry the DDC's outgoing dependency edges (e.g. material -> texture,
        // scene -> mesh) into the catalog row so the Content Browser dependency
        // graph sees them without re-fetching the .pack.json body.
        const nonBinAsset = productAssetByGuid(runResult.value.product, guidLower);
        const importedRow: PackIndexEntry =
          packUrl !== undefined
            ? {
                guid: raw.guid,
                relativeUrl: packUrl,
                kind: raw.kind,
                sourcePath: raw.sourcePath,
                // Same as the binary arm: preserve the derived display name the
                // field-by-field rebuild would otherwise drop.
                ...(raw.name !== undefined ? { name: raw.name } : {}),
                ...(raw.metadata !== undefined ? { metadata: raw.metadata } : {}),
                ...(nonBinAsset?.refs !== undefined
                  ? { refs: nonBinAsset.refs.map((ref) => ref.guid) }
                  : {}),
              }
            : nonBinAsset?.refs !== undefined
              ? { ...raw, refs: nonBinAsset.refs.map((ref) => ref.guid) }
              : raw;
        importedRows.set(guidLower, importedRow);
        const idx = catalog.findIndex((e) => e.guid.toLowerCase() === guidLower);
        if (idx >= 0) catalog[idx] = importedRow;
        allEntries.push(importedRow);
      }
    }

    if ('pack' in runResult.value) {
      // Best-effort: persist the pack JSON to the on-disk DDC so a future
      // build-mode pre-import (or out-of-process tool) can see it. The dev
      // request path itself reads from the in-memory `metaPackBodies` map
      // (set above), not from this file, so a write failure here is
      // diagnostic-only and does not block the import.
      const packJson = metaPackBodies.get(packUrl ?? '');
      if (packUrl !== undefined && packJson !== undefined && firstSubGuid !== undefined) {
        try {
          const packPath = ddcPath(cwd, `${firstSubGuid}.meta.pack`);
          await mkdir(dirname(packPath), { recursive: true });
          await writeFile(packPath, packJson);
        } catch (e) {
          console.warn('[forgeax-pack] persist DDC pack failed:', e);
        }
      }
    }

    return allEntries;
  }

  // M4 / w32 (AC-20): build the ImporterRegistry from the plugin options
  // at init time so the HTTP route has importers to dispatch to.
  const importerRegistry = new ImporterRegistry();
  const importers = opts.importers ?? [];
  for (const imp of importers) {
    importerRegistry.register(imp);
  }
  // UiAsset author sources are a first-party pack product. Register the
  // importer at the plugin boundary so every dev/build transport path shares
  // the same registry even when an app only declares pluginPack({ roots }).
  // Explicit host wiring may still replace it by key for tests or extensions.
  if (importerRegistry.get('ui') === undefined) {
    importerRegistry.register({ key: 'ui', ...createUiImporter() });
  }
  // P2 (feat-20260629 D-3): the host importer key set the catalog fold layer
  // uses to drive default passthrough vs raw-source rows. Engine built-in arms
  // fold unconditionally and are NOT part of this set.
  const registeredImporterKeys: ReadonlySet<string> = new Set(
    importerRegistry.registeredImporters(),
  );

  // M4 / w32 (AC-20) + feat-20260608 round-2: create the filesystem adapter
  // for the import runner. `decodeImage` and `readSibling` are wired here so
  // the gltfImporter's three image-source paths (bufferView / data: URI /
  // external URI sibling read) actually produce textures at build time --
  // without these the runner returns `import-internal-error` (the runner's
  // default `decodeImage` throws), the build silently falls through the `!ok`
  // branch (line ~898), and gltf scene/mesh/material rows never get their
  // hashed `.pack.json` overlay (production runtime then reads the source
  // .gltf as JSON, finds no `assets[]`, and loadByGuid<SceneAsset> fails
  // with `asset-not-found`). Engine fix per AGENTS.md "Demo failures route
  // to engine fixes, not workarounds": the demo's loadByGuid path does not
  // work without this wiring.
  const fsForImport: ImportRunnerFs = {
    async readSource(sourcePath: string) {
      try {
        const buf = await readFile(sourcePath);
        return { ok: true, value: new Uint8Array(buf) };
      } catch (e) {
        return { ok: false, error: e };
      }
    },
    async readSibling(sourcePath: string, uri: string) {
      try {
        const dir = dirname(sourcePath);
        const buf = await readFile(resolve(dir, uri));
        return { ok: true, value: new Uint8Array(buf) };
      } catch (e) {
        return { ok: false, error: e };
      }
    },
    async decodeImage(bytes, mimeType, importSettings) {
      // Lazy-import the Node-only parseImage so the build path stays
      // browser-safe at module load time (parseImage is an `@forgeax/engine-image`
      // sub-export gated by feat-20260524-browser-safe-subexports).
      const { parseImage } = await import('@forgeax/engine-image/parse-image');
      const colorSpace =
        importSettings.colorSpace === 'srgb' || importSettings.colorSpace === 'linear'
          ? importSettings.colorSpace
          : 'linear';
      const mipmap = importSettings.mipmap === true;
      const decoded = parseImage(bytes, mimeType, { colorSpace, mipmap });
      if (!decoded.ok) return decoded;
      const tex = decoded.value;
      // bug-20260610: format MUST agree with colorSpace (sRGB textures need
      // the `-srgb` GPU format suffix so the sampling hardware decodes the
      // perceptual gamma curve). A hardcoded `rgba8unorm` produced a
      // (format=linear, colorSpace=srgb) mismatch -- the runtime
      // prepareTextureUpload then either rejected the upload (image-format-
      // unsupported) or sampled the texture without sRGB decoding, which
      // washed every albedo to a uniform mid-grey on Sponza (#332 follow-up).
      const format = colorSpace === 'srgb' ? ('rgba8unorm-srgb' as const) : ('rgba8unorm' as const);
      return {
        ok: true,
        value: {
          texture: {
            kind: 'texture' as const,
            data: tex.bytes,
            width: tex.width,
            height: tex.height,
            format,
            colorSpace,
            mipmap,
          },
          bytes: tex.bytes,
        },
      };
    },
  };

  // ─── configureServer (dev mode) ──────────────────────────────────────────

  function configureServer(server: ViteDevServerLike): void {
    // Async startup: scan roots to build the initial catalog.
    const { roots } = resolvePackBuildInputs(opts);
    Promise.all([buildCatalog(roots, opts.base, registeredImporterKeys), buildGuidToMetaMap(roots)])
      .then(([rawEntries, g2m]) => {
        // The dev catalog passes the discoverable bare-source texture rows
        // straight through, with the per-asset import overlay applied so any
        // already-imported `.bin` row survives the rebuild (monotonic import).
        // The runtime loader (import-on-demand sentinel) routes any non-`.bin`
        // texture row to the dev transport for lazy import; keeping the row
        // discoverable is the precondition for Sponza's catalog-first
        // findTextureGuidByFilename.
        catalog = applyImportedRows(rawEntries);
        guidToMeta = g2m;
        urlToAbs = buildUrlToAbs(catalog);
        catalogReady = true;

        // Watch sidecars and every source file via
        // node:fs.watch. fs.watch is non-recursive on Linux; for dev
        // HMR precision we watch each root directory tree individually
        // by relying on the recursive option (available on macOS and
        // Windows, and polyfilled by the Node 22+ watcher on Linux).
        //
        // Sidecar / pack-index changes rebuild the catalog. Every other source
        // file only emits `full-reload`: its bytes may feed an engine importer
        // or a host-defined importer, while catalog rows come from sidecars.
        //
        // Debounce + dedup (feedback 2026-07-06): a single file write on
        // Windows fans out into N `fs.watch` events; each one previously
        // rebuilt the catalog and broadcast `full-reload`, spamming the log
        // and interrupting continuous editor interactions (drag/resize).
        // We coalesce all events in a WATCH_DEBOUNCE_MS window into ONE
        // catalog rebuild + ONE `full-reload` + one consolidated log, and
        // drop events whose file content (sidecar) or mtime:size signature
        // (source) is unchanged since the last flush -- byte-identical
        // rewrites and `touch`es no longer reload the page.
        const pendingSidecars = new Map<string, { filename: string; eventType: string }>();
        const pendingSources = new Map<string, { filename: string; eventType: string }>();
        const lastSidecarContent = new Map<string, string>();
        const lastSourceSig = new Map<string, string>();
        let flushTimer: ReturnType<typeof setTimeout> | undefined;

        const flush = async (): Promise<void> => {
          const sidecars = [...pendingSidecars.entries()];
          const sources = [...pendingSources.entries()];
          pendingSidecars.clear();
          pendingSources.clear();

          // Content dedup for sidecars: skip a rewrite whose bytes match the
          // last-seen content. A read failure (the file was deleted) clears the
          // cache and still counts as a change so the catalog rebuild drops the
          // stale rows.
          const changedSidecars: Array<{ filename: string; eventType: string }> = [];
          for (const [abs, info] of sidecars) {
            let content: string | undefined;
            try {
              content = await readFile(abs, 'utf-8');
            } catch {
              lastSidecarContent.delete(abs);
              changedSidecars.push(info);
              continue;
            }
            if (lastSidecarContent.get(abs) === content) continue;
            lastSidecarContent.set(abs, content);
            changedSidecars.push(info);
          }

          // mtime:size dedup for sources: catalog rows are produced
          // from sidecars, not source bytes, so we only need to know whether the
          // bytes actually changed before asking the browser to re-fetch them.
          const changedSources: Array<{ filename: string; eventType: string }> = [];
          for (const [abs, info] of sources) {
            let sig: string | undefined;
            try {
              const s = await stat(abs);
              sig = `${s.mtimeMs}:${s.size}`;
            } catch {
              lastSourceSig.delete(abs);
              changedSources.push(info);
              continue;
            }
            if (lastSourceSig.get(abs) === sig) continue;
            lastSourceSig.set(abs, sig);
            changedSources.push(info);
          }

          if (changedSidecars.length === 0 && changedSources.length === 0) return;

          // Rebuild the catalog once (only when a sidecar actually changed) so
          // the browser's first post-reload fetch lands on the new state.
          if (changedSidecars.length > 0) {
            try {
              const [rawEntries2, g2m2] = await Promise.all([
                buildCatalog(roots, opts.base, registeredImporterKeys),
                buildGuidToMetaMap(roots),
              ]);
              catalog = applyImportedRows(rawEntries2);
              guidToMeta = g2m2;
              urlToAbs = buildUrlToAbs(catalog);
            } catch (err: unknown) {
              console.warn('[forgeax-pack] rebuild catalog error:', err);
            }
          }

          // One full-reload for the whole batch, then one structured event per
          // changed file (the editor Content Browser re-queries `/__pack/index`
          // only for `sidecar` events).
          server.ws?.send({ type: 'full-reload' });
          for (const info of changedSidecars) {
            emitAssetChanged(server, info.filename, info.eventType, 'sidecar');
          }
          for (const info of changedSources) {
            emitAssetChanged(server, info.filename, info.eventType, 'source');
          }

          const parts: string[] = [];
          if (changedSidecars.length > 0) parts.push(`${changedSidecars.length} sidecar`);
          if (changedSources.length > 0) parts.push(`${changedSources.length} source`);
          console.warn(`[forgeax-pack] assets changed: ${parts.join(', ')} (reloaded)`);
        };

        const WATCH_DEBOUNCE_MS = 150;
        const scheduleFlush = (): void => {
          if (flushTimer !== undefined) clearTimeout(flushTimer);
          flushTimer = setTimeout(() => {
            flushTimer = undefined;
            void flush();
          }, WATCH_DEBOUNCE_MS);
          flushTimer.unref();
        };

        for (const root of roots) {
          try {
            const watcher = fsWatch(root, { recursive: true }, (eventType, filename) => {
              if (filename === null) return;
              const isSidecar = filename.endsWith('.meta.json') || filename.endsWith('.pack.json');
              const isUi =
                filename.endsWith('.ui.html') ||
                filename.endsWith('.ui.css') ||
                filename.endsWith('.woff2') ||
                filename.endsWith('.webp') ||
                filename.endsWith('.svg');
              const isSource = !isSidecar && !isUi;

              const abs = resolve(root, filename);
              if (isSidecar || isUi) pendingSidecars.set(abs, { filename, eventType });
              else if (isSource) pendingSources.set(abs, { filename, eventType });
              scheduleFlush();
            });
            watcher.unref();
            watcher.on('error', () => {});
          } catch {
            // Root does not exist yet — skip watching.
          }
        }
      })
      .catch((err: unknown) => {
        console.warn('[forgeax-pack] startup scan error:', err);
        catalogReady = true;
      });

    // Register connect middleware for /__pack/* routes + the
    // dev-mode `/pack-index.json` route (charter P4 consistent
    // abstraction: production emits the same file via generateBundle).
    server.middlewares.use(async (req, res, next) => {
      const url = req.url ?? '';

      if (url === '/__pack/index' || url === '/pack-index.json') {
        // Wait for catalog to be ready (short-circuit if already built).
        if (!catalogReady) {
          await new Promise<void>((resolve) => {
            const interval = setInterval(() => {
              if (catalogReady) {
                clearInterval(interval);
                resolve();
              }
            }, 5);
          });
        }
        res.setHeader('Content-Type', 'application/json');
        res.end(JSON.stringify(catalog));
        return;
      }

      const lookupPrefix = '/__pack/lookup/';
      if (url.startsWith(lookupPrefix)) {
        if (!catalogReady) {
          await new Promise<void>((resolve) => {
            const interval = setInterval(() => {
              if (catalogReady) {
                clearInterval(interval);
                resolve();
              }
            }, 5);
          });
        }
        const guid = url.slice(lookupPrefix.length);
        const entry = catalog.find((e) => e.guid.toLowerCase() === guid.toLowerCase());
        if (entry === undefined) {
          res.statusCode = 404;
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify({ error: 'not-found', guid }));
          return;
        }
        res.setHeader('Content-Type', 'application/json');
        res.end(JSON.stringify(entry));
        return;
      }

      // M4 / w32 (AC-20): POST /__import/:guid — lazy import adapter.
      // The dev form of ImportTransport calls this endpoint when a DDC is
      // missing. The route reads the declaring meta sidecar, dispatches the
      // importer via the import runner, writes the DDC (.pack.json) to the
      // source directory, upgrades the catalog, and returns the updated
      // PackIndexEntry[] for the imported GUID + its sub-assets.
      const importPrefix = '/__import/';
      if (url.startsWith(importPrefix)) {
        // Only POST triggers import; GET returns 405 so AI users get a
        // clear signal.
        if ((req as { method?: string }).method !== 'POST') {
          res.statusCode = 405;
          res.setHeader('Allow', 'POST');
          res.setHeader('Content-Type', 'application/json');
          res.end(
            JSON.stringify({
              error: 'method-not-allowed',
              hint: 'use POST to trigger lazy import',
            }),
          );
          return;
        }
        if (!catalogReady) {
          await new Promise<void>((resolve) => {
            const interval = setInterval(() => {
              if (catalogReady) {
                clearInterval(interval);
                resolve();
              }
            }, 5);
          });
        }
        const guid = url.slice(importPrefix.length);
        const guidLower = guid.toLowerCase();

        // Precise 404: the GUID is declared by no sidecar at all (vs. declared
        // but not an importable texture, which falls through to a 422 below).
        if (guidToMeta.get(guidLower) === undefined && importedRows.get(guidLower) === undefined) {
          res.statusCode = 404;
          res.setHeader('Content-Type', 'application/json');
          res.end(
            JSON.stringify({
              error: 'meta-not-found',
              guid,
              hint: 'no sidecar declares this GUID',
            }),
          );
          return;
        }

        // M4 / w20 (D-2): per-meta import coalescing. When this GUID belongs
        // to a gltf sidecar (whose import produces multiple sub-assets per
        // meta), we import the WHOLE meta once and overlay all rows at once.
        // Concurrent requests for the same metaPath share the same in-flight
        // Promise via inFlightMetaImports. The per-asset path below
        // (importOneTexture + inFlightImports) handles image sidecars where a
        // single GUID maps to a single texture asset.
        //
        // Dispatch: if the GUID belongs to an already-imported row (per-asset
        // path), return it immediately. Otherwise route through per-meta for
        // gltf sidecars, per-asset for everything else.
        const alreadyImported = importedRows.get(guidLower);
        if (alreadyImported !== undefined) {
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify([alreadyImported]));
          return;
        }

        const metaPath = guidToMeta.get(guidLower);
        let resultEntries: PackIndexEntry[];

        // Only route through per-meta for gltf / fbx importers; image/audio/font
        // sidecars produce a single sub-asset row and the per-asset path
        // (importOneTexture) is the right verb. fbx behaves like gltf — single
        // .fbx source file produces multiple sub-asset rows (mesh / material /
        // scene / texture / skeleton / skin / animation-clip) that need to be
        // imported together via runImport (feat-20260615-fbx-importer-via-sdk).
        let isMultiAssetMeta = false;
        if (metaPath !== undefined) {
          try {
            const metaRaw = JSON.parse(await readFile(metaPath, 'utf-8')) as {
              importer?: string;
            };
            // UI author sources are products with companion artifacts. They
            // must use the per-meta importer path so startMetaImport can
            // finalize HTML/CSS and publish the in-memory /__ui payloads;
            // treating them as textures returns an empty result (422).
            isMultiAssetMeta =
              metaRaw.importer === 'gltf' ||
              metaRaw.importer === 'fbx' ||
              metaRaw.importer === 'ui';
          } catch {
            // Unreadable meta — fall through to per-asset.
          }
        }

        // Both arms throw the structured ImportError on a REAL failure
        // (fail-fast): per-meta via `startMetaImport`'s `throw runResult.error`,
        // per-asset via `importOneTexture`'s `throw new ImportError`. One shared
        // catch surfaces `.code` + `detail.reason` so AI/human users see the
        // actual cause (e.g. `fbx-mesh-type-unsupported`, or a decode-failure
        // reason) instead of a generic `import-failed`.
        try {
          if (metaPath !== undefined && isMultiAssetMeta) {
            // Per-meta path: coalesce on metaPath.
            let inflightMeta = inFlightMetaImports.get(metaPath);
            if (inflightMeta === undefined) {
              inflightMeta = startMetaImport(metaPath).finally(() =>
                inFlightMetaImports.delete(metaPath),
              );
              inFlightMetaImports.set(metaPath, inflightMeta);
            }
            resultEntries = await inflightMeta;
            // Filter to the requested GUID's row.
            const requested = resultEntries.find((e) => e.guid.toLowerCase() === guidLower);
            resultEntries = requested !== undefined ? [requested] : [];
          } else {
            // Fallback per-asset path (image sidecars, single-texture import).
            let inflight = inFlightImports.get(guidLower);
            if (inflight === undefined) {
              inflight = importOneTexture(guidLower).finally(() =>
                inFlightImports.delete(guidLower),
              );
              inFlightImports.set(guidLower, inflight);
            }
            resultEntries = await inflight;
          }
        } catch (e) {
          const err = e as {
            code?: string;
            hint?: string;
            detail?: { reason?: string };
          };
          res.statusCode = 422;
          res.setHeader('Content-Type', 'application/json');
          res.end(
            JSON.stringify({
              error: 'import-failed',
              guid,
              code: err.code ?? 'import-internal-error',
              reason: err.detail?.reason ?? (e instanceof Error ? e.message : String(e)),
              hint: err.hint ?? 'importer threw while converting the source',
            }),
          );
          return;
        }

        if (resultEntries.length === 0) {
          // Benign empty result: the GUID is declared but not an importable
          // texture (non-texture kind / unknown extension -- `importOneTexture`
          // returns `[]` for these), or the per-meta filter found no matching
          // row. Real cook failures throw above and never reach here.
          res.statusCode = 422;
          res.setHeader('Content-Type', 'application/json');
          res.end(
            JSON.stringify({
              error: 'import-failed',
              guid,
              hint: 'GUID declared but not an importable texture (non-texture kind, unknown extension, or no matching sub-asset row)',
            }),
          );
          return;
        }
        res.setHeader('Content-Type', 'application/json');
        res.end(JSON.stringify(resultEntries));
        return;
      }

      // bug-20260610: serve in-memory `.pack.json` bodies produced by
      // `startMetaImport` for non-binary gltf sub-assets (mesh / scene /
      // material). The runtime's `fetchPackFile` GETs the catalog row's
      // `relativeUrl`; without this route the request would fall through to
      // Vite's default 404 (or, worse, hit the raw `.gltf` URL when the row
      // was not rewritten and serve gltf JSON, which has no `assets[]`).
      const uiBody = uiArtifactBodies.get(url);
      if (uiBody !== undefined) {
        res.statusCode = 200;
        res.setHeader('Content-Type', uiBody.mimeType);
        res.end(uiBody.bytes);
        return;
      }

      if (url.startsWith(DEV_PACK_PREFIX)) {
        const body = metaPackBodies.get(url);
        if (body === undefined) {
          res.statusCode = 404;
          res.setHeader('Content-Type', 'application/json');
          res.end(
            JSON.stringify({
              error: 'pack-body-not-found',
              url,
              hint: 'no startMetaImport has produced this pack URL yet',
            }),
          );
          return;
        }
        res.statusCode = 200;
        res.setHeader('Content-Type', 'application/json');
        res.end(body);
        return;
      }

      // Serve external assets (e.g. submodule textures) that Vite
      // cannot find under the app root.  The catalog's `relativeUrl`
      // paths are normalized (no `..` segments); the `urlToAbs` map
      // resolves each URL to its absolute source path.
      const absPath = urlToAbs.get(url);
      if (absPath !== undefined) {
        try {
          const buf = await readFile(absPath);
          const mime = mimeFromPath(absPath);
          if (mime !== undefined) {
            res.setHeader('Content-Type', mime);
          }
          res.statusCode = 200;
          res.end(buf);
          return;
        } catch {
          res.statusCode = 404;
          res.end('Not found');
          return;
        }
      }

      next();
    });
  }

  // ─── generateBundle (build mode) ─────────────────────────────────────────

  async function generateBundle(this: MinimalPluginContext): Promise<void> {
    const cwd = process.cwd();
    const { roots, basePrefix } = resolvePackBuildInputs(opts);
    const sharedManifest = process.env.FORGEAX_SHARED_APP_INPUTS_MANIFEST;
    if (sharedManifest !== undefined) {
      const shared = loadSharedPackInput(sharedManifest);
      if (process.env.FORGEAX_SHARED_APP_INPUTS_MODE !== 'catalog-only') {
        if (shared.payloadRoot === undefined) {
          throw new Error(`shared pack manifest lacks payload for full mode: ${sharedManifest}`);
        }
        const emitted = new Set<string>();
        for (const entry of shared.catalog) {
          const outputPath = entry.relativeUrl.replace(/^\/+/, '');
          if (emitted.has(outputPath)) continue;
          emitted.add(outputPath);
          this.emitFile({
            type: 'asset',
            fileName: outputPath,
            source: readFileSync(resolve(shared.payloadRoot, outputPath)),
          });
        }
      }
      this.emitFile({
        type: 'asset',
        fileName: 'pack-index.json',
        source: JSON.stringify(projectSharedPackCatalog(shared.catalog, opts.base)),
      });
      return;
    }
    const { paths } = loadAssetConfig(cwd);
    const entries = await buildCatalog(roots, opts.base, registeredImporterKeys);

    // Import step (M3 / w28, AC-21): the image import no longer inlines
    // `parseImage` here. It routes through the build-time `imageImporter`
    // (@forgeax/engine-image) -- the same Importer the @forgeax/engine-import
    // runner dispatches `meta.importer === 'image'` to (D-9: the image import
    // SSOT lives in engine-image). For each `kind: 'texture'` row we build a
    // one-subAsset `ImportContext` and call `imageImporter.import(ctx)`; the
    // returned `TextureAsset` payload carries the imported RGBA bytes (`data`)
    // plus `width` / `height`, which we extract into a hashed `.bin`
    // (D-1: untouched bytes; D-2: `name: '<guid-lowercase>'` + Rollup default
    // `assetFileNames` => `assets/<guid>-<hash>.bin`). The returned
    // `referenceId` bridges the GUID namespace to Rollup's hash namespace;
    // `getFileName(refId)` resolves the final hashed filename after emit.
    //
    // Pack-index entries are mutated in place (`relativeUrl` -> hashed `.bin`;
    // `metadata.width / height` from the imported image). Non-image rows
    // (`mesh` / `scene` / `material`) flow through untouched. .hdr rows
    // (D-2: .hdr extension -> imageImporter HDR arm) are imported here;
    // other unknown extensions (no standard mime / no .hdr discriminant)
    // are passed through with the raw relativeUrl so the catalog is not
    // silently dropped.
    // AC-01: guid -> meta path so the texture arm can honor an explicit
    // importSettings.compression override (built once, reused by the mesh arm
    // below as allGuidToMeta).
    const guidToMetaBuild = await buildGuidToMetaMap(roots);
    const importedEntries: PackIndexEntry[] = [];
    for (const entry of entries) {
      // gap-3 (w5): the pure import logic now lives in the shared
      // `importTextureEntry` SSOT (import-texture.ts), used by both this build
      // arm and the dev POST /__import path (D-1). The shared fn returns
      // `{ skipped }` for any row that is not an importable image / .hdr
      // (non-texture kind, missing metadata, unknown extension, importer
      // throw, or absent produced asset) -- pass those through unchanged.
      const imported = await importTextureEntry(entry, { cwd });
      if ('skipped' in imported) {
        // Surface real import failures as a warning; silent pass-through for
        // benign non-importable rows (non-texture / unknown extension). The
        // benign-vs-real classification is the shared fn's `real` flag (one
        // SSOT), no longer a `skipped` string-prefix match here.
        if (imported.real) {
          console.warn(`[forgeax-pack] ${imported.skipped}`);
        }
        importedEntries.push(entry);
        continue;
      }
      // emitFile name '<guid-lowercase>' (D-2) + originalFileName for
      // Rollup's automatic addWatchFile hook (research F1). The imported bytes
      // (rgba8 / rgba16float) come from the shared import fn; the relativeUrl
      // rewrite (emitFile + getFileName) stays here, the build arm owning it.
      // (B) Texture arm build: compress after importTextureEntry, before emitFile (D-3).
      // AC-01: honor an explicit importSettings.compression override from the meta.
      const texBuildOverride = await readOverrideFromMeta(
        guidToMetaBuild.get(entry.guid.toLowerCase()),
      );
      const compressedTex = await compressArtifact({
        bytes: imported.bytes,
        kind: 'texture',
        isPackJson: false,
        ...(texBuildOverride !== undefined ? { override: texBuildOverride } : {}),
        // Carry the importer's resolved delivery encoding so a Basis KTX2 row
        // records its basis-* discriminant (loader transcode dispatch) instead
        // of the STRATEGY_TABLE 'none' default (which fell through to a scheme=1
        // KTX2 reject). Build path SSOT with the dev arm.
        ...(imported.metadata.compression !== undefined
          ? { alreadyCompressed: imported.metadata.compression }
          : {}),
      });
      const refId = this.emitFile({
        type: 'asset',
        name: `${entry.guid.toLowerCase()}.bin`,
        originalFileName: resolve(cwd, entry.sourcePath),
        source: compressedTex.compressed,
      });
      // getFileName surfaces 'assets/<guid>-<hash>.bin' once Rollup has
      // finished hash resolution (always available inside generateBundle).
      const hashedPath = this.getFileName(refId);
      importedEntries.push({
        guid: entry.guid,
        relativeUrl: projectPackIndexUrl(basePrefix, hashedPath),
        kind: entry.kind,
        sourcePath: entry.sourcePath,
        metadata: imported.metadata,
        compression: compressedTex.compression,
      });
    }

    // M4 / w33 (AC-21): full pre-import for the shipped form. For every meta
    // sidecar, call the import runner to produce the DDC (.pack.json) and emit
    // it as a Rollup asset. This ensures the shipped bundle carries all DDC
    // artefacts, not just the texture .bin import output. After this step the
    // catalog entries' relativeUrl fields point to the hashed asset paths
    // (Rollup names), matching the import step's convention.
    //
    // For meta files whose DDC already exists on disk (e.g. pre-generated by
    // the CLI), the import runner re-imports them idempotently (GUID
    // import-stable iron law produces the same output). The runner also
    // validates the GUID set; `importer: 'shader'` is skipped.
    //
    // guidToMetaBuild (built above the texture arm) tells us which meta declares
    // each entry's GUID. Group entries by their declaring meta so we call
    // `runImport` once per meta (one pass produces all sub-assets).
    const guidSeen = new Set<string>();
    const finalizedUiUrls = new Map<string, string>();

    for (const entry of importedEntries) {
      if (guidSeen.has(entry.guid.toLowerCase())) continue;
      const metaPath = guidToMetaBuild.get(entry.guid.toLowerCase());
      if (metaPath === undefined) {
        // Legacy pack entries (pre-existing .pack.json or non-meta rows).
        guidSeen.add(entry.guid.toLowerCase());
        continue;
      }

      // Parse the meta and call runImport for the whole sidecar at once.
      let rm: unknown;
      try {
        rm = JSON.parse(await readFile(metaPath, 'utf-8'));
      } catch {
        // Skip unreadable meta; the entry stays in the catalog as-is.
        guidSeen.add(entry.guid.toLowerCase());
        continue;
      }
      const meta = rm as {
        importer: string;
        source?: string;
        importSettings?: unknown;
        subAssets: ReadonlyArray<{ guid: string; sourceIndex: number; kind: string }>;
      };

      // Mark all sub-asset GUIDs as seen so we don't re-import this meta twice.
      for (const sub of meta.subAssets) {
        guidSeen.add(sub.guid.toLowerCase());
      }

      // Pass1 (the import step above) already decoded these images, emitted the
      // hashed `.bin`, and folded width/height/format/colorSpace/mipmap into the
      // pack-index row's `relativeUrl` + `metadata`. The runtime textureLoader
      // dispatches on `entry.kind === 'texture'` and reads only that `.bin` + the
      // inline pack-index metadata; it never fetches the per-image `.pack.json`
      // that runImport would emit here. Re-running the full import for an
      // `importer: 'image'` meta therefore re-decodes every image a second time
      // and emits a `.pack.json` Rollup asset nothing consumes. Skip it. glTF /
      // FBX metas (whose texture sub-assets are a disjoint GUID set produced by
      // their own importer) and any other importer still flow through below.
      if (meta.importer === 'image') {
        continue;
      }

      const sourceResult = resolveAssetSource(metaPath, meta.source, paths);
      if (!sourceResult.ok) {
        console.warn(
          `[forgeax-pack] source resolution failed for ${metaPath}: ${sourceResult.error.code} — skipping pre-import`,
        );
        continue;
      }

      const runMeta: RunImportMeta = {
        importer: meta.importer,
        source: sourceResult.value,
        subAssets: meta.subAssets,
      };
      if (meta.importSettings !== undefined) {
        (runMeta as { importSettings?: Readonly<Record<string, unknown>> }).importSettings =
          meta.importSettings as Readonly<Record<string, unknown>>;
      }

      const runResult = await runImport(runMeta, importerRegistry, fsForImport);
      if (!runResult.ok) {
        const reason =
          (runResult.error.detail as { reason?: string } | undefined)?.reason ??
          runResult.error.hint ??
          '';
        // `importer-not-registered` is a legitimate skip: this build simply
        // does not wire that importer (e.g. an .hdr sidecar in a build that
        // registers only the image importer), so the catalog keeps the source
        // sourcePath as the runtime fallback. Warn and continue.
        if (runResult.error.code === 'importer-not-registered') {
          // eslint-disable-next-line no-console
          console.warn(
            `[forgeax-pack] no importer registered for ${metaPath}; keeping source fallback (${reason})`,
          );
          continue;
        }
        // Any other failure means a WIRED importer failed to convert the source
        // (e.g. fbx-mesh-type-unsupported surfacing as import-internal-error). The
        // .pack.json DDC never overlays the catalog, so the build would emit a
        // pack-index pointing at the raw source and ship a guaranteed
        // blank-screen demo with only a stderr warning. Fail-fast
        // (architecture-principles §5 + AGENTS.md "demo failures route to engine
        // fixes") so the gap can never be mistaken for a green build.
        throw new Error(
          `[forgeax-pack] pre-import failed for ${metaPath}: ${runResult.error.code} - ${reason}`,
        );
      }
      if ('skipped' in runResult.value) {
        // Skip shader sidecars in pre-import; the catalog keeps the original
        // sourcePath as the runtime fallback.
        continue;
      }

      if (meta.importer === 'ui') {
        const uiGuid = meta.subAssets[0]?.guid;
        if (uiGuid === undefined) continue;
        const artifactPaths = new Map<string, string>();
        const transportArtifacts = projectUiBuildArtifacts(
          runResult.value.product.artifacts,
          (artifact) => artifact.path,
        );
        for (const artifact of transportArtifacts) {
          const ref = this.emitFile({
            type: 'asset',
            name: artifact.path,
            originalFileName: artifact.path,
            source: artifact.bytes,
          });
          artifactPaths.set(artifact.path, this.getFileName(ref));
        }
        const finalized = finalizeUiArtifact(runResult.value.product as never, {
          artifactUrl: (artifact) =>
            projectPackIndexUrl(basePrefix, artifactPaths.get(artifact.path) ?? artifact.path),
        });
        if (!finalized.ok) {
          throw new Error(
            `[forgeax-pack] UI finalizer failed for ${metaPath}: ${finalized.error.code}`,
          );
        }
        const uiRef = this.emitFile({
          type: 'asset',
          name: `${uiGuid}.ui.json`,
          originalFileName: metaPath,
          source: JSON.stringify(finalized.value.asset),
        });
        const uiPath = projectPackIndexUrl(basePrefix, this.getFileName(uiRef));
        finalizedUiUrls.set(uiGuid.toLowerCase(), uiPath);
        const rowIndex = importedEntries.findIndex(
          (entry) => entry.guid.toLowerCase() === uiGuid.toLowerCase(),
        );
        if (rowIndex >= 0 && importedEntries[rowIndex] !== undefined) {
          importedEntries[rowIndex] = { ...importedEntries[rowIndex], relativeUrl: uiPath };
        }
        continue;
      }

      // Emit the .pack.json DDC as a Rollup asset. Use the same name-based
      // emit pattern as the image import step so Rollup assigns a hashed asset
      // path. The pack is a JSON string; we fold the binary (.bin) emission
      // into the same loop when `bins` is present (multi-bin, keyed by
      // lowercased GUID).
      const { pack, bins } = runResult.value;
      const productByGuid = productAssetsByGuid(runResult.value.product);
      if ('pack' in runResult.value) {
        const packJson = JSON.stringify(pack);
        const packRefId = this.emitFile({
          type: 'asset',
          name: `${meta.subAssets[0]?.guid ?? 'pack'}.pack.json`,
          originalFileName: metaPath,
          source: packJson,
        });
        const hashedPackPath = this.getFileName(packRefId);

        // Update all entries from this meta to point to the hashed pack path.
        for (const sub of meta.subAssets) {
          const idx = importedEntries.findIndex(
            (e) => e.guid.toLowerCase() === sub.guid.toLowerCase(),
          );
          if (idx >= 0 && importedEntries[idx] !== undefined) {
            const existing = importedEntries[idx];
            if (existing !== undefined) {
              // Carry the DDC's outgoing dependency edges into the shipped
              // pack-index row so the prod Content Browser dependency graph
              // sees them without re-fetching the .pack.json body.
              const ddcAsset = productByGuid.get(sub.guid.toLowerCase());
              importedEntries[idx] = {
                ...existing,
                relativeUrl: projectPackIndexUrl(basePrefix, hashedPackPath),
                ...(ddcAsset?.refs !== undefined
                  ? { refs: ddcAsset.refs.map((ref) => ref.guid) }
                  : {}),
              };
            }
          }
        }
      }

      // M4 / w21: emit each binary blob from the bins map (one per
      // sub-asset GUID) and update the corresponding importedEntries row
      // so the texture's relativeUrl points to the hashed .bin asset
      // (matching the image-import first-pass convention, where the
      // runtime textureLoader expects a `.bin`-suffixed URL).
      //
      // feat-20260608 round-2 finding 4: metadata.colorSpace is overlaid
      // from the imported TextureAsset's payload (the gltfImporter derived
      // colorSpace per-image via deriveTextureColorSpace -- D-3 walk of
      // material slot bindings). Without this, build-catalog's default
      // 'linear' bleed through to pack-index even when the actual texture
      // is sRGB baseColor. AI users reading pack-index would see
      // metadata.colorSpace='linear' for srgb baseColors, a misleading
      // contradiction with the TextureAsset POD the runtime registers.
      if (bins !== undefined && bins.size > 0) {
        for (const [guidLower, bytes] of bins.entries()) {
          // (D) Mesh bins arm build: compress after packMeshBin, before emitFile (D-3).
          // Determine artifact kind from the matching imported entry.
          const binEntry = importedEntries.find(
            (e) =>
              e.guid.toLowerCase() === guidLower && (e.kind === 'texture' || e.kind === 'mesh'),
          );
          const compressKind: 'mesh' | 'texture' = binEntry?.kind === 'mesh' ? 'mesh' : 'texture';
          // AC-01: explicit per-asset compression override from importSettings.
          const meshOverride = readCompressionOverride(meta.importSettings);
          const compressedBin = await compressArtifact({
            bytes,
            kind: compressKind,
            isPackJson: false,
            ...(meshOverride !== undefined ? { override: meshOverride } : {}),
          });
          const refId = this.emitFile({
            type: 'asset',
            name: `${guidLower}.bin`,
            originalFileName: metaPath,
            source: compressedBin.compressed,
          });
          const hashedBinPath = this.getFileName(refId);

          // Look up the imported texture's payload colorSpace + format from
          // the produced pack so the row metadata reflects per-image truth
          // rather than the catalog's safe-default fallback.
          const importedAsset = productByGuid.get(guidLower);
          const importedPayload = importedAsset?.payload as
            | {
                colorSpace?: 'srgb' | 'linear';
                format?: GPUTextureFormat;
                mipmap?: boolean;
                width?: number;
                height?: number;
              }
            | undefined;

          // Update the importedEntries row for this texture or mesh GUID so
          // its relativeUrl points to the hashed .bin asset. bug-20260610 Fix
          // A widens this filter from texture-only: mesh sub-assets now also
          // emit a sibling `<guid>.bin` (vertices + indices + JSON tail), so
          // their catalog row must point at the hashed .bin URL just like
          // texture rows. Materials / scenes still keep their `.pack.json`
          // relativeUrl since they have no `bins` entry. The colorSpace
          // metadata overlay block below stays guarded by `metadata?.kind ===
          // 'texture'`, which naturally skips for mesh (no metadata.kind set).
          const texIdx = importedEntries.findIndex(
            (e) =>
              e.guid.toLowerCase() === guidLower && (e.kind === 'texture' || e.kind === 'mesh'),
          );
          if (texIdx >= 0 && importedEntries[texIdx] !== undefined) {
            const existing = importedEntries[texIdx];
            if (existing !== undefined) {
              let overlaidMetadata: ImageMetadata | undefined;
              if (existing.metadata?.kind === 'texture') {
                overlaidMetadata = {
                  kind: 'texture',
                  format: importedPayload?.format ?? existing.metadata.format,
                  colorSpace: importedPayload?.colorSpace ?? existing.metadata.colorSpace,
                  mipmap: importedPayload?.mipmap ?? existing.metadata.mipmap,
                  ...(importedPayload?.width !== undefined ? { width: importedPayload.width } : {}),
                  ...(importedPayload?.height !== undefined
                    ? { height: importedPayload.height }
                    : {}),
                };
              }
              importedEntries[texIdx] = {
                ...existing,
                relativeUrl: projectPackIndexUrl(basePrefix, hashedBinPath),
                ...(overlaidMetadata !== undefined
                  ? { metadata: overlaidMetadata }
                  : existing.metadata !== undefined
                    ? { metadata: existing.metadata }
                    : {}),
                compression: compressedBin.compression,
              };
            }
          }
        }
      }
    }

    const productionCatalog = dedupeFinalizedUiEntries(importedEntries, finalizedUiUrls);
    this.emitFile({
      type: 'asset',
      fileName: 'pack-index.json',
      source: JSON.stringify(productionCatalog),
    });
  }

  return {
    name: 'forgeax:pack',
    configureServer,
    generateBundle,
  };
}

/** Package version string (debug tag). */
export const VITE_PLUGIN_PACK_PACKAGE_VERSION = '0.0.0';
