import { readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ScriptablePackPublicationSnapshot } from '@forgeax/engine-ddc';
import { createAcceptedPublicationStore, resolveDdcRoot } from '@forgeax/engine-ddc';
import {
  canonicalScriptableSourcePath,
  commitImportPublication,
  discardImportPublication,
  ImporterRegistry,
  type ImportRunnerFs,
  type RunImportMeta,
  restoreImportPublication,
} from '@forgeax/engine-import';
import type { CatalogBuildResult } from '@forgeax/engine-pack/build';
import {
  currentProjectionFor,
  metaPathForGuid,
  upgradeLegacyAuthoredPack,
} from '@forgeax/engine-pack/build';
import type { ScanSourceDeclaration } from '@forgeax/engine-pack/scanner';
import {
  type PackIndexEntry,
  RUNTIME_CATALOG_SNAPSHOT_SCHEMA,
  type RuntimeAssetBinding,
  runtimeScopePath,
} from '@forgeax/engine-types';
import { createPluginBuild } from './build/plugin-build.js';
import { publishAuthoredDevPacks as publishAuthoredDevPacksOwner } from './dev/authored-pack-publication.js';
import { startMetaImport as startMetaImportOwner } from './dev/meta-import.js';
import {
  createPluginServer,
  type PluginServerProjectionState,
  type PluginServerState,
} from './dev/plugin-server.js';
import type {
  AssetHostRefreshPolicy,
  PluginPack,
  PluginPackInternalOptions,
  PluginPackOptions,
} from './plugin-contract.js';
import { projectRuntimeDiagnostics } from './runtime-diagnostics.js';
import { structuredPluginError } from './structured-plugin-error.js';

const COOKED_CURRENT_PROJECTION = currentProjectionFor('imported-output', 'cooked');

const DIRECT_CURRENT_PROJECTION = currentProjectionFor('internal-asset', 'direct');

const AUTHORED_COOKED_CURRENT_PROJECTION = currentProjectionFor('internal-asset', 'cooked');

const VIRTUAL_RUNTIME_ID = 'virtual:forgeax/pack-runtime';
const VIRTUAL_RUNTIME_TRANSPORT_ID = 'virtual:forgeax/pack-runtime-transport';

type PackViteConfig = {
  readonly base: string;
  readonly command?: 'build' | 'serve';
};

function virtualRuntimeSource(
  binding: RuntimeAssetBinding | undefined,
  command: PackViteConfig['command'],
): string {
  if (command === 'build') {
    // Keep the dev-only transport out of production chunks altogether. The
    // binding remains in the build projection because Pack publication tuples
    // still need the same scope identity when the registry reads the emitted
    // static catalog; only the dev import transport is absent.
    const serializedBinding = binding === undefined ? 'undefined' : JSON.stringify(binding);
    return `// AUTO-GENERATED by @forgeax/engine-vite-plugin-pack.\nexport const runtimeBinding = ${serializedBinding};\nexport function createRuntimeAssetImportTransport() { return undefined; }\n`;
  }
  const serializedBinding = binding === undefined ? 'undefined' : JSON.stringify(binding);
  return `// AUTO-GENERATED by @forgeax/engine-vite-plugin-pack.\nimport { createDevImportTransport } from '${VIRTUAL_RUNTIME_TRANSPORT_ID}';\nexport const runtimeBinding = ${serializedBinding};\nexport function createRuntimeAssetImportTransport(binding = runtimeBinding) {\n  return binding === undefined ? undefined : createDevImportTransport(binding);\n}\n`;
}

function runtimeDdcRoot(projectDdcRoot: string, binding: RuntimeAssetBinding | undefined): string {
  return resolve(
    projectDdcRoot,
    'runtime',
    binding === undefined
      ? 'unbound'
      : `${binding.scopeId.replace(/[^a-zA-Z0-9._-]/g, '_')}-${binding.generation}`,
  );
}

export function pluginPack(opts: PluginPackOptions = {}): PluginPack {
  return createPluginPackInternal(opts);
}

export function reloadAssetHost(): AssetHostRefreshPolicy {
  return (server) => server.ws?.send({ type: 'full-reload' });
}

export function createPluginPackInternal(
  opts: PluginPackInternalOptions = {},
  internal: Pick<PluginPackInternalOptions, 'transportBase'> = {},
) {
  const composition = { ...opts, ...internal };
  const explicitTransportBase = composition.transportBase;
  let transportBase = explicitTransportBase;
  let projectDdcRoot = composition.ddc?.projectDdcRoot ?? resolveDdcRoot(process.cwd());
  const emptyCatalogProjection = (): CatalogBuildResult => ({
    schemaVersion: 'catalog-legacy-v1',
    entries: [],
    authority: 'authoritative',
    diagnostics: [],
    declarations: new Map(),
    sourceDeclarations: new Map(),
  });
  const state: PluginServerState = {
    catalogProjection: emptyCatalogProjection(),
    importedGuids: new Set(),
    metaPackBodies: new Map(),
    devArtifactBodies: new Map(),
  };
  let refreshAcceptedSource: (sourcePath: string) => Promise<void> = async () => {};
  let inFlightSourceRefresh: Promise<void> | undefined;
  let publishCatalogDelta:
    | ((delta: import('@forgeax/engine-types').CatalogDelta) => void)
    | undefined;
  const publicationStore = createAcceptedPublicationStore();
  const inFlightMetaImports = new Map<
    string,
    {
      readonly metaContents: string;
      readonly promise: Promise<PackIndexEntry[]>;
    }
  >();
  const DEV_PACK_PREFIX = '/__forgeax-ddc/';

  function projectScopedEntry(entry: PackIndexEntry): PackIndexEntry {
    if (entry.publication === undefined) return entry;
    const sourcePath = canonicalScriptableSourcePath(entry.sourcePath);
    return {
      ...entry,
      sourcePath,
      publication: {
        ...entry.publication,
        sourcePath,
        receipt: { ...entry.publication.receipt, sourcePath },
        ...(entry.publication.failure === undefined
          ? {}
          : { failure: { ...entry.publication.failure, sourcePath } }),
      },
    };
  }
  function resetDevState(): void {
    state.catalogProjection = emptyCatalogProjection();
    state.importedGuids.clear();
    inFlightMetaImports.clear();
    state.metaPackBodies.clear();
    state.devArtifactBodies.clear();
  }
  async function publishAuthoredDevPacks(
    raw: readonly PackIndexEntry[],
    projection: PluginServerProjectionState,
    declarations: ReadonlyMap<string, ScanSourceDeclaration> = state.catalogProjection
      .sourceDeclarations,
    signal?: AbortSignal,
    runtimeBinding?: RuntimeAssetBinding,
  ): Promise<PackIndexEntry[]> {
    return publishAuthoredDevPacksOwner(raw, {
      opts: composition,
      transportBase,
      metaPackBodies: projection.metaPackBodies,
      devArtifactBodies: projection.devArtifactBodies,
      importedGuids: projection.importedGuids,
      publicationCandidates: projection.publicationCandidates,
      publicationStore,
      ...(runtimeBinding === undefined ? {} : { scopeId: runtimeBinding.scopeId }),
      sourceDeclarations: declarations,
      importerRegistry,
      fsForImport,
      ...(signal === undefined ? {} : { signal }),
      currentProjection: COOKED_CURRENT_PROJECTION,
      directProjection: DIRECT_CURRENT_PROJECTION,
      authoredCookedProjection: AUTHORED_COOKED_CURRENT_PROJECTION,
    });
  }
  function scopedPackageUrl(binding: RuntimeAssetBinding, packageUrl: string): string {
    const base = binding.packageUrlBase.replace(/\/+$/, '');
    const rawUrl = packageUrl.startsWith('/') ? packageUrl : `/${packageUrl}`;
    const scopedNamespace = runtimeScopePath(binding, 'asset');
    const hostBase = base.endsWith(scopedNamespace) ? base.slice(0, -scopedNamespace.length) : '';
    const internalUrl =
      hostBase.length > 0 && (rawUrl === hostBase || rawUrl.startsWith(`${hostBase}/`))
        ? rawUrl.slice(hostBase.length) || '/'
        : rawUrl;
    const scopedPath = runtimeScopePath(binding, `asset${internalUrl}`);
    if (base.length === 0) return scopedPath;
    return base.endsWith(scopedNamespace) ? `${base}${internalUrl}` : `${base}${scopedPath}`;
  }
  function scopedCatalogResponse(binding: RuntimeAssetBinding) {
    const projection = state.catalogProjection;
    return {
      schemaVersion: RUNTIME_CATALOG_SNAPSHOT_SCHEMA,
      scopeId: binding.scopeId,
      generation: binding.generation,
      authority: projection.authority,
      entries: projection.entries.map((entry) => ({
        ...projectScopedEntry(entry),
        packageUrl: scopedPackageUrl(binding, entry.packageUrl),
      })),
      diagnostics: projectRuntimeDiagnostics(projection.diagnostics),
    };
  }
  async function ensureVersionedMetaImport(
    metaPath: string,
    declaration?: RunImportMeta,
    signal?: AbortSignal,
    projection?: PluginServerProjectionState,
    runtimeBinding?: RuntimeAssetBinding,
  ): Promise<PackIndexEntry[]> {
    const effectiveDeclaration = declaration ?? state.catalogProjection.declarations.get(metaPath);
    if (effectiveDeclaration === undefined) {
      throw structuredPluginError({
        code: 'catalog-declaration-missing',
        expected: 'the accepted inventory to retain the validated Meta declaration',
        hint: 'rebuild the Catalog and retry the import route',
        detail: { stage: 'route', metaPath },
      });
    }
    const metaContents = effectiveDeclaration.sourceRevision ?? metaPath;
    const existing = inFlightMetaImports.get(metaPath);
    if (
      projection === undefined &&
      existing !== undefined &&
      existing.metaContents === metaContents
    ) {
      return existing.promise;
    }
    let promise: Promise<PackIndexEntry[]>;
    promise = (async () => {
      if (projection === undefined && existing !== undefined) {
        try {
          await existing.promise;
        } catch {
          // A newer Meta revision is also the recovery path for a failed cook.
        }
      }
      const target = projection ?? {
        catalogProjection: state.catalogProjection,
        importedGuids: state.importedGuids,
        metaPackBodies: state.metaPackBodies,
        devArtifactBodies: state.devArtifactBodies,
        pendingImportPublications: undefined,
      };
      return startMetaImportOwner(metaPath, {
        ddcRoot: (_cwd, binding) => runtimeDdcRoot(projectDdcRoot, binding),
        ...(runtimeBinding === undefined ? {} : { runtimeBinding }),
        getCatalogProjection: () => target.catalogProjection,
        setCatalogProjection: (projection) => {
          target.catalogProjection = projection;
        },
        importedGuids: target.importedGuids,
        metaPackBodies: target.metaPackBodies,
        devArtifactBodies: target.devArtifactBodies,
        importerRegistry,
        fsForImport,
        publishCatalogDelta,
        cookedProjection: COOKED_CURRENT_PROJECTION,
        ...(target.pendingImportPublications === undefined
          ? {}
          : { pendingImportPublications: target.pendingImportPublications }),
        ...(signal === undefined ? {} : { signal }),
        declaration: effectiveDeclaration,
      });
    })().finally(() => {
      if (inFlightMetaImports.get(metaPath)?.promise === promise) {
        inFlightMetaImports.delete(metaPath);
      }
    });
    if (projection === undefined) inFlightMetaImports.set(metaPath, { metaContents, promise });
    return promise;
  }
  async function ensureMetaPackBody(url: string): Promise<string | undefined> {
    const existing = state.metaPackBodies.get(url);
    const authoredSourcePath = state.catalogProjection.entries.find(
      (entry) => entry.packageUrl === url && entry.sourcePath.endsWith('.pack.json'),
    )?.sourcePath;
    if (authoredSourcePath !== undefined) {
      const sourceDeclaration = state.catalogProjection.sourceDeclarations.get(
        resolve(authoredSourcePath),
      );
      if (existing !== undefined && sourceDeclaration?.format === 'pack.json')
        if (
          (await readFile(sourceDeclaration.sourcePath, 'utf8').catch(() => undefined)) ===
          sourceDeclaration.sourceText
        )
          return existing;
      if (inFlightSourceRefresh === undefined)
        inFlightSourceRefresh = refreshAcceptedSource(authoredSourcePath).finally(
          () => (inFlightSourceRefresh = undefined),
        );
      await inFlightSourceRefresh;
      const declaration = state.catalogProjection.sourceDeclarations.get(
        resolve(authoredSourcePath),
      );
      if (declaration?.format !== 'pack.json') {
        throw structuredPluginError({
          code: 'catalog-declaration-missing',
          expected: 'the accepted inventory to retain the authored Pack declaration',
          hint: 'rerun inventory before serving the authored Pack body',
          detail: { stage: 'route', sourcePath: authoredSourcePath },
        });
      }
      const refreshed = state.metaPackBodies.get(url);
      if (refreshed !== undefined) return refreshed;
      const pack = upgradeLegacyAuthoredPack(declaration.value);
      const cooked =
        pack.schemaVersion === '2.0.0' &&
        pack.assets !== undefined &&
        pack.assets.some((asset) => asset.execution === 'cooked');
      if (cooked) {
        const refreshedAfterCook = state.metaPackBodies.get(url);
        if (refreshedAfterCook !== undefined) return refreshedAfterCook;
      }
      if (pack.schemaVersion !== '2.0.0' || pack.assets === undefined || cooked) {
        throw structuredPluginError({
          code: 'pack-source-output-invalid',
          expected: 'an authored Pack source without cooked assets for direct transport',
          hint: 'move cooked assets into a registered producer or rebuild the authored Pack',
          detail: { stage: 'route', sourcePath: authoredSourcePath },
        });
      }
      return declaration.value.schemaVersion === '2.0.0'
        ? (declaration.sourceText ?? JSON.stringify(pack))
        : JSON.stringify(pack);
    }
    if (existing !== undefined) return existing;
    if (!url.startsWith(DEV_PACK_PREFIX) || !url.endsWith('.pack.json')) return undefined;

    const guid = url.slice(DEV_PACK_PREFIX.length, -'.pack.json'.length).toLowerCase();
    if (guid.includes('/')) return undefined;
    const metaPath = metaPathForGuid(state.catalogProjection.declarations, guid);
    if (metaPath === undefined) return undefined;

    await ensureVersionedMetaImport(metaPath, state.catalogProjection.declarations.get(metaPath));
    return state.metaPackBodies.get(url);
  }
  const importerRegistry = new ImporterRegistry();
  for (const imp of opts.importers ?? []) {
    importerRegistry.register(imp);
  }
  const registeredImporterKeys: ReadonlySet<string> = new Set(
    importerRegistry.registeredImporters(),
  );
  const fsForImport: ImportRunnerFs = {
    async readSource(sourcePath: string) {
      try {
        const buf = await readFile(sourcePath);
        return { ok: true, value: new Uint8Array(buf) };
      } catch (e) {
        return { ok: false, error: e };
      }
    },
    async readSibling(sourcePath: string, uri: string) {
      try {
        const dir = dirname(sourcePath);
        const buf = await readFile(resolve(dir, uri));
        return { ok: true, value: new Uint8Array(buf) };
      } catch (e) {
        return { ok: false, error: e };
      }
    },
    ...importerRegistry.contextCapabilities(),
  };
  const serverLifecycle = createPluginServer({
    opts: composition,
    get transportBase() {
      return transportBase;
    },
    get projectDdcRoot() {
      return projectDdcRoot;
    },
    setProjectDdcRoot: (root) => {
      projectDdcRoot = root;
    },
    registeredImporterKeys,
    catalogVisibility: (input) => importerRegistry.shouldPublishCatalog(input),
    resetState: resetDevState,
    scopedPackageUrl,
    scopedCatalogResponse,
    state,
    setSourceRefresh: (refresh) => {
      refreshAcceptedSource = refresh;
    },
    callbacks: {
      publishAuthoredDevPacks,
      ensureMetaImport: ensureVersionedMetaImport,
      commitGeneration: async (candidate, signal) => {
        const publicationSnapshots = new Map<string, ScriptablePackPublicationSnapshot>();
        for (const sourcePath of candidate.publicationCandidates.keys()) {
          publicationSnapshots.set(sourcePath, publicationStore.observe(sourcePath));
        }
        const rollback = async (): Promise<void> => {
          try {
            await Promise.all(
              [...candidate.pendingImportPublications.values()].map((publication) =>
                restoreImportPublication(publication),
              ),
            );
            for (const [sourcePath, publication] of candidate.publicationCandidates) {
              publicationStore.discard(sourcePath, publication);
              const snapshot = publicationSnapshots.get(sourcePath);
              if (snapshot !== undefined) publicationStore.restore(sourcePath, snapshot);
            }
          } finally {
            // The production catch path calls discard after this callback rejects. These
            // candidates are already rolled back, so expose no second lifecycle mutation.
            candidate.pendingImportPublications.clear();
            candidate.publicationCandidates.clear();
          }
        };
        const assertOpen = (): void => {
          if (signal?.aborted === true) {
            throw structuredPluginError({
              code: 'stale-generation',
              expected: 'the production generation to remain current during commit',
              hint: 'retry the rebuild after the active generation settles',
              detail: { stage: 'commit', subject: 'production-generation' },
            });
          }
        };
        try {
          assertOpen();
          for (const [subject, publication] of candidate.pendingImportPublications) {
            assertOpen();
            const result = await commitImportPublication(publication);
            if (!result.ok) {
              // A newer generation may have superseded this lease while the
              // DDC commit was in flight.  Keep the strict DDC CAS outcome,
              // but classify the cancelled loser as stale so the caller can
              // retry the active generation instead of surfacing commit-failed.
              assertOpen();
              throw structuredPluginError({
                code: 'commit-failed',
                expected: 'DDC to commit every staged Meta import publication',
                hint: result.error.hint,
                detail: { stage: 'commit', subject },
                cause: result.error,
              });
            }
            if (!result.transportPersisted) {
              for (const guid of publication.input.publishedGuids) {
                candidate.importedGuids.delete(guid.toLowerCase());
              }
              console.warn('[forgeax-pack] persist DDC pack failed:', {
                code: 'source-package-ddc-persistence-failed',
                guid: publication.input.guid,
                packageUrl: publication.input.transport?.path,
              });
            }
          }
          for (const [sourcePath, publication] of candidate.publicationCandidates) {
            assertOpen();
            const result = await publicationStore.commit(
              sourcePath,
              { envelope: publication },
              () => undefined,
            );
            if (!result.ok) {
              assertOpen();
              throw structuredPluginError({
                code: 'commit-failed',
                expected: 'DDC to commit every accepted authored Pack publication',
                hint: result.error.reason,
                detail: { stage: 'commit', sourcePath },
                cause: result.error,
              });
            }
          }
          assertOpen();
        } catch (error) {
          await rollback();
          throw error;
        }
      },
      discardPublications: (candidates) => {
        for (const [sourcePath, candidate] of candidates) {
          publicationStore.discard(sourcePath, candidate);
        }
      },
      discardImportPublications: async (candidates) => {
        await Promise.all(
          [...candidates.values()].map((candidate) => discardImportPublication(candidate)),
        );
      },
      ensureMetaPackBody,
      setCatalogDeltaPublisher: (publisher) => {
        publishCatalogDelta = publisher;
      },
    },
  });
  const buildLifecycle = createPluginBuild({
    opts: composition,
    get transportBase() {
      return transportBase;
    },
    registeredImporterKeys,
    catalogVisibility: (input) => importerRegistry.shouldPublishCatalog(input),
    importerRegistry,
    fsForImport,
    cookedCurrentProjection: COOKED_CURRENT_PROJECTION,
    directCurrentProjection: DIRECT_CURRENT_PROJECTION,
    authoredCookedCurrentProjection: AUTHORED_COOKED_CURRENT_PROJECTION,
  });
  let viteCommand: PackViteConfig['command'];
  return {
    name: 'forgeax:pack',
    resolveId(source: string): string | null {
      if (source === VIRTUAL_RUNTIME_ID) return VIRTUAL_RUNTIME_ID;
      if (source === VIRTUAL_RUNTIME_TRANSPORT_ID) {
        return fileURLToPath(import.meta.resolve('@forgeax/engine-runtime'));
      }
      return null;
    },
    load(id: string): string | null {
      return id === VIRTUAL_RUNTIME_ID
        ? virtualRuntimeSource(composition.runtimeBinding, viteCommand)
        : null;
    },
    configResolved(config: PackViteConfig): void {
      viteCommand = config.command;
      if (explicitTransportBase === undefined) transportBase = config.base;
    },
    rebind: serverLifecycle.rebind,
    runtimeBinding: serverLifecycle.runtimeBinding,
    configureServer: serverLifecycle.configureServer,
    generateBundle: buildLifecycle.generateBundle,
    closeBundle: async () => {
      await serverLifecycle.close();
      await buildLifecycle.closeBundle();
    },
  };
}

/** Package version string (debug tag). */
