import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ScriptablePackPublicationSnapshot } from '@forgeax/engine-ddc';
import { createAcceptedPublicationStore, DdcLifecycle, resolveDdcRoot } from '@forgeax/engine-ddc';
import {
  canonicalScriptableSourcePath,
  commitImportPublication,
  ImporterRegistry,
  type ImportRunnerFs,
  type RunImportMeta,
  restoreImportPublication,
  type StagedImportPublication,
  stageImportPublication,
} from '@forgeax/engine-import';
import type { CatalogBuildResult } from '@forgeax/engine-pack/build';
import {
  bindRuntimePackScope,
  currentProjectionFor,
  metaPathForGuid,
} from '@forgeax/engine-pack/build';
import { validatePluginAsset } from '@forgeax/engine-pack/runtime';
import { declaredPackAssets, type ScanSourceDeclaration } from '@forgeax/engine-pack/scanner';
import { projectDirectPackJson } from '@forgeax/engine-pack/source';
import {
  type PackIndexEntry,
  RUNTIME_CATALOG_SNAPSHOT_SCHEMA,
  type RuntimeAssetBinding,
  type RuntimeCatalogSnapshot,
  runtimeScopePath,
} from '@forgeax/engine-types';
import {
  type AssetBindingCatalog,
  assetBindingDeclarationSource,
  assetBindingModuleSource,
} from './build/asset-bindings.js';
import { createPluginBuild } from './build/plugin-build.js';
import { publishAuthoredDevPacks as publishAuthoredDevPacksOwner } from './dev/authored-pack-publication.js';
import { startMetaImport as startMetaImportOwner } from './dev/meta-import.js';
import {
  createPluginServer,
  type PluginServerProjectionState,
  type PluginServerState,
} from './dev/plugin-server.js';
import { sourceDeclarationForCatalogPath } from './dev/source-path.js';
import { scopedEntry } from './dev/transport-routes.js';
import { HttpArtifactCompression } from './http-artifact.js';
import type {
  AssetHostRefreshPolicy,
  PluginPack,
  PluginPackInternalOptions,
  PluginPackOptions,
} from './plugin-contract.js';
import { projectRuntimeDiagnostics } from './runtime-diagnostics.js';
import { structuredPluginError } from './structured-plugin-error.js';

const COOKED_CURRENT_PROJECTION = currentProjectionFor('imported-output', 'cooked');

const DIRECT_CURRENT_PROJECTION = currentProjectionFor('internal-asset', 'direct');

const AUTHORED_COOKED_CURRENT_PROJECTION = currentProjectionFor('internal-asset', 'cooked');

const VIRTUAL_RUNTIME_ID = 'virtual:forgeax/pack-runtime';
const VIRTUAL_RUNTIME_TRANSPORT_ID = 'virtual:forgeax/pack-runtime-transport';
const VIRTUAL_ASSETS_ID = 'virtual:forgeax/assets';
const RESOLVED_VIRTUAL_ASSETS_ID = `\0${VIRTUAL_ASSETS_ID}`;
const VIRTUAL_ASSETS_DTS_ID = 'virtual:forgeax/assets.d.ts';
const RESOLVED_VIRTUAL_ASSETS_DTS_ID = `\0${VIRTUAL_ASSETS_DTS_ID}`;

function extractSceneEntityKeys(payload: Readonly<Record<string, unknown>>): readonly string[] {
  const entities = payload.entities;
  if (entities === null || typeof entities !== 'object' || Array.isArray(entities)) return [];
  return Object.keys(entities);
}

type PackViteConfig = {
  readonly base: string;
  readonly root?: string;
  readonly command?: 'build' | 'serve';
};

function virtualRuntimeSource(
  binding: RuntimeAssetBinding | undefined,
  command: PackViteConfig['command'],
): string {
  if (command === 'build') {
    // Keep the dev-only transport out of production chunks altogether. The
    // binding remains in the build projection because Pack publication tuples
    // still need the same scope identity when the registry reads the emitted
    // static catalog; only the dev import transport is absent.
    const serializedBinding = binding === undefined ? 'undefined' : JSON.stringify(binding);
    return `// AUTO-GENERATED by @forgeax/engine-vite-plugin-pack.\nexport const runtimeBinding = ${serializedBinding};\nexport function createRuntimeAssetImportTransport() { return undefined; }\n`;
  }
  const serializedBinding = binding === undefined ? 'undefined' : JSON.stringify(binding);
  return `// AUTO-GENERATED by @forgeax/engine-vite-plugin-pack.\nimport { createDevImportTransport } from '${VIRTUAL_RUNTIME_TRANSPORT_ID}';\nexport const runtimeBinding = ${serializedBinding};\nexport function createRuntimeAssetImportTransport(binding = runtimeBinding) {\n  return binding === undefined ? undefined : createDevImportTransport(binding);\n}\n`;
}

function runtimeDdcRoot(projectDdcRoot: string, binding: RuntimeAssetBinding | undefined): string {
  return resolve(
    projectDdcRoot,
    'runtime',
    binding === undefined
      ? 'unbound'
      : `${binding.scopeId.replace(/[^a-zA-Z0-9._-]/g, '_')}-${binding.generation}`,
  );
}

export function pluginPack(opts: PluginPackOptions = {}): PluginPack {
  return createPluginPackInternal(opts);
}

export function reloadAssetHost(): AssetHostRefreshPolicy {
  return (server) => server.ws?.send({ type: 'full-reload' });
}

export function createPluginPackInternal(
  opts: PluginPackInternalOptions = {},
  internal: Pick<PluginPackInternalOptions, 'transportBase'> = {},
) {
  const composition = { ...opts, ...internal };
  const explicitTransportBase = composition.transportBase;
  let transportBase = explicitTransportBase;
  let declarationTarget = resolve(process.cwd(), '.forgeax', 'generated', 'assets.d.ts');
  let projectDdcRoot = composition.ddc?.projectDdcRoot ?? resolveDdcRoot(process.cwd());
  const emptyCatalogProjection = (): CatalogBuildResult => ({
    schemaVersion: 'catalog-legacy-v1',
    entries: [],
    authority: 'authoritative',
    diagnostics: [],
    declarations: new Map(),
    sourceDeclarations: new Map(),
  });
  const state: PluginServerState = {
    artifactCompression: new HttpArtifactCompression(),
    catalogProjection: emptyCatalogProjection(),
    importedGuids: new Set(),
    metaPackBodies: new Map(),
    devArtifactBodies: new Map(),
  };
  let refreshAcceptedSource: (sourcePath: string) => Promise<void> = async () => {};
  let inFlightSourceRefresh: Promise<void> | undefined;
  let publishCatalogDelta:
    | ((delta: import('@forgeax/engine-types').CatalogDelta) => void)
    | undefined;
  const publicationStore = createAcceptedPublicationStore();
  const inFlightMetaImports = new Map<
    string,
    {
      readonly metaContents: string;
      readonly promise: Promise<PackIndexEntry[]>;
    }
  >();
  const DEV_PACK_PREFIX = '/__forgeax-ddc/';

  function devPackGuidForUrl(url: string): string | undefined {
    if (!url.startsWith(DEV_PACK_PREFIX) || !url.endsWith('.pack.json')) return undefined;
    const guid = url.slice(DEV_PACK_PREFIX.length, -'.pack.json'.length).toLowerCase();
    return guid.length === 0 || guid.includes('/') ? undefined : guid;
  }

  function persistedArtifactPaths(pack: unknown): readonly string[] | undefined {
    if (pack === null || typeof pack !== 'object' || !('assets' in pack)) return undefined;
    const assets = (pack as { readonly assets?: unknown }).assets;
    if (!Array.isArray(assets)) return undefined;
    const paths: string[] = [];
    for (const asset of assets) {
      if (asset === null || typeof asset !== 'object' || !('artifacts' in asset)) return undefined;
      const artifacts = (asset as { readonly artifacts?: unknown }).artifacts;
      if (artifacts === null || typeof artifacts !== 'object' || Array.isArray(artifacts)) {
        return undefined;
      }
      for (const descriptor of Object.values(artifacts)) {
        if (
          descriptor === null ||
          typeof descriptor !== 'object' ||
          !('path' in descriptor) ||
          typeof (descriptor as { readonly path?: unknown }).path !== 'string'
        ) {
          return undefined;
        }
        paths.push((descriptor as { readonly path: string }).path);
      }
    }
    return paths;
  }

  function devArtifactClosureReady(body: string): boolean {
    try {
      const paths = persistedArtifactPaths(JSON.parse(body));
      return (
        paths?.every((path) => state.devArtifactBodies.has(`${DEV_PACK_PREFIX}${path}`)) ?? false
      );
    } catch {
      return false;
    }
  }

  function scopedCatalogEntry(binding: RuntimeAssetBinding, entry: PackIndexEntry): PackIndexEntry {
    const scoped = scopedEntry({ scopedPackageUrl }, binding, entry);
    if (scoped.publication === undefined) return scoped;
    const sourcePath = canonicalScriptableSourcePath(entry.sourcePath);
    return {
      ...scoped,
      sourcePath,
      publication: {
        ...scoped.publication,
        sourcePath,
        receipt: { ...scoped.publication.receipt, sourcePath },
        ...(scoped.publication.failure === undefined
          ? {}
          : { failure: { ...scoped.publication.failure, sourcePath } }),
      },
    };
  }
  function resetDevState(): void {
    state.catalogProjection = emptyCatalogProjection();
    state.importedGuids.clear();
    inFlightMetaImports.clear();
    state.metaPackBodies.clear();
    state.devArtifactBodies.clear();
    invalidateBindingModules();
  }
  function invalidateBindingModules(): void {
    serverLifecycle.invalidateModules([
      RESOLVED_VIRTUAL_ASSETS_ID,
      RESOLVED_VIRTUAL_ASSETS_DTS_ID,
      VIRTUAL_RUNTIME_ID,
    ]);
  }
  function assetBindingCatalog(
    catalogProjection: CatalogBuildResult = state.catalogProjection,
  ): AssetBindingCatalog {
    const assets = catalogProjection.entries.flatMap((entry) =>
      entry.sourceKey === undefined
        ? []
        : [{ guid: entry.guid, sourceKey: entry.sourceKey, kind: entry.kind }],
    );
    const scenes = [...catalogProjection.sourceDeclarations.values()].flatMap((source) => {
      if (source.format !== 'pack.json') return [];
      return declaredPackAssets(source.value).flatMap((asset) => {
        if (asset.kind !== 'scene' || asset.sourceKey === undefined) return [];
        const entityKeys = extractSceneEntityKeys(asset.payload);
        return entityKeys.length > 0 ? [{ sourceKey: asset.sourceKey, entityKeys }] : [];
      });
    });
    return { assets, scenes };
  }
  async function writeAssetBindingDeclaration(
    catalogProjection: CatalogBuildResult = state.catalogProjection,
  ): Promise<void> {
    const source = assetBindingDeclarationSource(assetBindingCatalog(catalogProjection));
    try {
      if ((await readFile(declarationTarget, 'utf8')) === source) return;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
    const generatedDirectory = dirname(declarationTarget);
    const temporary = resolve(
      generatedDirectory,
      `assets.d.ts.${process.pid}.${Math.random().toString(16).slice(2)}.tmp`,
    );
    await mkdir(generatedDirectory, { recursive: true });
    try {
      await writeFile(temporary, source, 'utf8');
      await rename(temporary, declarationTarget);
    } catch (error) {
      await rm(temporary, { force: true });
      throw error;
    }
  }
  async function publishAuthoredDevPacks(
    raw: readonly PackIndexEntry[],
    projection: PluginServerProjectionState,
    declarations: ReadonlyMap<string, ScanSourceDeclaration> = state.catalogProjection
      .sourceDeclarations,
    signal?: AbortSignal,
    runtimeBinding?: RuntimeAssetBinding,
  ): Promise<PackIndexEntry[]> {
    return publishAuthoredDevPacksOwner(raw, {
      opts: composition,
      transportBase,
      metaPackBodies: projection.metaPackBodies,
      devArtifactBodies: projection.devArtifactBodies,
      importedGuids: projection.importedGuids,
      publicationCandidates: projection.publicationCandidates,
      publicationStore,
      previousCatalogEntries: state.catalogProjection.entries,
      ...(runtimeBinding === undefined ? {} : { scopeId: runtimeBinding.scopeId }),
      sourceDeclarations: declarations,
      importerRegistry,
      fsForImport,
      ...(signal === undefined ? {} : { signal }),
      currentProjection: COOKED_CURRENT_PROJECTION,
      directProjection: DIRECT_CURRENT_PROJECTION,
      authoredCookedProjection: AUTHORED_COOKED_CURRENT_PROJECTION,
    });
  }
  function scopedPackageUrl(binding: RuntimeAssetBinding, packageUrl: string): string {
    const base = binding.packageUrlBase.replace(/\/+$/, '');
    const rawUrl = packageUrl.startsWith('/') ? packageUrl : `/${packageUrl}`;
    const scopedNamespace = runtimeScopePath(binding, 'asset');
    const hostBase = base.endsWith(scopedNamespace) ? base.slice(0, -scopedNamespace.length) : '';
    const internalUrl =
      hostBase.length > 0 && (rawUrl === hostBase || rawUrl.startsWith(`${hostBase}/`))
        ? rawUrl.slice(hostBase.length) || '/'
        : rawUrl;
    const scopedPath = runtimeScopePath(binding, `asset${internalUrl}`);
    if (base.length === 0) return scopedPath;
    return base.endsWith(scopedNamespace) ? `${base}${internalUrl}` : `${base}${scopedPath}`;
  }
  let serializedCatalog:
    | { projection: CatalogBuildResult; binding: RuntimeAssetBinding; body: string }
    | undefined;

  function scopedCatalogBody(binding: RuntimeAssetBinding): string {
    const projection = state.catalogProjection;
    // Accepted and lazy publications replace the projection, even within one
    // runtime generation. Keep one body for that projection and its wire scope;
    // never cache only by generation or bypass the route's freshness barrier.
    if (
      serializedCatalog?.projection === projection &&
      serializedCatalog.binding.scopeId === binding.scopeId &&
      serializedCatalog.binding.generation === binding.generation &&
      serializedCatalog.binding.packageUrlBase === binding.packageUrlBase &&
      serializedCatalog.binding.authority === binding.authority &&
      (binding.authority !== 'degraded' ||
        serializedCatalog.binding.diagnostics === binding.diagnostics)
    ) {
      return serializedCatalog.body;
    }
    const body = JSON.stringify({
      schemaVersion: RUNTIME_CATALOG_SNAPSHOT_SCHEMA,
      scopeId: binding.scopeId,
      generation: binding.generation,
      authority: binding.authority === 'degraded' ? ('degraded' as const) : projection.authority,
      entries: projection.entries.map((entry) => scopedCatalogEntry(binding, entry)),
      diagnostics:
        binding.authority === 'degraded'
          ? (binding.diagnostics ?? projectRuntimeDiagnostics(projection.diagnostics))
          : projectRuntimeDiagnostics(projection.diagnostics),
    } satisfies RuntimeCatalogSnapshot);
    serializedCatalog = { projection, binding, body };
    return body;
  }
  async function ensureVersionedMetaImport(
    metaPath: string,
    declaration?: RunImportMeta,
    signal?: AbortSignal,
    projection?: PluginServerProjectionState,
    runtimeBinding?: RuntimeAssetBinding,
  ): Promise<PackIndexEntry[]> {
    const effectiveDeclaration = declaration ?? state.catalogProjection.declarations.get(metaPath);
    if (effectiveDeclaration === undefined) {
      throw structuredPluginError({
        code: 'catalog-declaration-missing',
        expected: 'the accepted inventory to retain the validated Meta declaration',
        hint: 'rebuild the Catalog and retry the import route',
        detail: { stage: 'route', metaPath },
      });
    }
    const metaContents = effectiveDeclaration.sourceRevision ?? metaPath;
    const existing = inFlightMetaImports.get(metaPath);
    if (
      projection === undefined &&
      existing !== undefined &&
      existing.metaContents === metaContents
    ) {
      return existing.promise;
    }
    let promise: Promise<PackIndexEntry[]>;
    promise = (async () => {
      if (projection === undefined && existing !== undefined) {
        try {
          await existing.promise;
        } catch {
          // A newer Meta revision is also the recovery path for a failed cook.
        }
      }
      const target = projection ?? {
        catalogProjection: state.catalogProjection,
        importedGuids: state.importedGuids,
        metaPackBodies: state.metaPackBodies,
        devArtifactBodies: state.devArtifactBodies,
        pendingImportPublications: undefined,
      };
      return startMetaImportOwner(metaPath, {
        ddcRoot: (_cwd, binding) => runtimeDdcRoot(projectDdcRoot, binding),
        ...(runtimeBinding === undefined ? {} : { runtimeBinding }),
        getCatalogProjection: () => target.catalogProjection,
        setCatalogProjection: (projection) => {
          target.catalogProjection = projection;
        },
        importedGuids: target.importedGuids,
        metaPackBodies: target.metaPackBodies,
        devArtifactBodies: target.devArtifactBodies,
        importerRegistry,
        cookers: opts.cookers,
        fsForImport,
        publishCatalogDelta,
        cookedProjection: COOKED_CURRENT_PROJECTION,
        ...(target.pendingImportPublications === undefined
          ? {}
          : { pendingImportPublications: target.pendingImportPublications }),
        ...(signal === undefined ? {} : { signal }),
        declaration: effectiveDeclaration,
      });
    })().finally(() => {
      if (inFlightMetaImports.get(metaPath)?.promise === promise) {
        inFlightMetaImports.delete(metaPath);
      }
    });
    if (projection === undefined) inFlightMetaImports.set(metaPath, { metaContents, promise });
    return promise;
  }
  async function restoreDdcPackBody(
    url: string,
    binding: RuntimeAssetBinding,
    existingBody?: string,
  ): Promise<string | undefined> {
    const guid = devPackGuidForUrl(url);
    if (guid === undefined) return undefined;
    try {
      const ddcRoot = runtimeDdcRoot(projectDdcRoot, binding);
      const current = await new DdcLifecycle(ddcRoot).readCurrentEntry(guid);
      if (
        current.head.state !== 'current' ||
        current.entry === null ||
        current.entry.guid.toLowerCase() !== guid ||
        current.entry.key !== current.head.currentKey
      ) {
        return undefined;
      }
      const publicationGeneration = state.catalogProjection.entries.find(
        (entry) => entry.guid.toLowerCase() === guid,
      )?.publication?.generation;
      const payloadGeneration =
        current.entry.payload !== null &&
        typeof current.entry.payload === 'object' &&
        !Array.isArray(current.entry.payload) &&
        typeof (current.entry.payload as { readonly generation?: unknown }).generation === 'number'
          ? (current.entry.payload as { readonly generation: number }).generation
          : undefined;
      const persistedGeneration = current.entry.receipt.publicationGeneration ?? payloadGeneration;
      const payload = bindRuntimePackScope(
        current.entry.payload,
        binding.scopeId,
        publicationGeneration ?? persistedGeneration ?? binding.generation,
      );
      const artifactPaths = persistedArtifactPaths(payload);
      const body = JSON.stringify(payload);
      if (existingBody !== undefined && existingBody !== body) return undefined;
      if (
        artifactPaths === undefined ||
        artifactPaths.some((path) => current.entry?.artifacts[path] === undefined)
      ) {
        return undefined;
      }
      for (const [path, artifact] of Object.entries(current.entry.artifacts)) {
        state.devArtifactBodies.set(`${DEV_PACK_PREFIX}${path}`, {
          bytes: artifact.bytes,
          mimeType: artifact.mediaType,
        });
      }
      if (existingBody === undefined) state.metaPackBodies.set(url, body);
      return body;
    } catch {
      // A corrupt or incomplete DDC entry is not a transport authority. Let
      // the declared producer repair it through the normal import path.
      return undefined;
    }
  }
  async function ensureMetaPackBody(
    url: string,
    runtimeBinding?: RuntimeAssetBinding,
  ): Promise<string | undefined> {
    const existing = state.metaPackBodies.get(url);
    const devImportPack = runtimeBinding !== undefined && devPackGuidForUrl(url) !== undefined;
    const needsProducerRecovery =
      devImportPack && (existing === undefined || !devArtifactClosureReady(existing));
    if (needsProducerRecovery) {
      const restored = await restoreDdcPackBody(url, runtimeBinding, existing);
      if (restored !== undefined) return existing ?? restored;
    }
    const dynamicInstance = state.catalogProjection.entries.find(
      (entry) =>
        entry.packageUrl === url &&
        entry.sourcePath.endsWith('.pack.json') &&
        entry.provenance?.provider === 'pack-ts',
    );
    // Dynamic v3 instances are materialized during the accepted production
    // generation and have no legacy source-refresh route. Their source path
    // is a Catalog identity, so serve the already staged body before trying to
    // resolve it as a cwd-relative declaration.
    if (existing !== undefined && dynamicInstance !== undefined) return existing;
    const authoredSourcePath = state.catalogProjection.entries.find(
      (entry) => entry.packageUrl === url && entry.sourcePath.endsWith('.pack.json'),
    )?.sourcePath;
    if (authoredSourcePath !== undefined) {
      const sourceDeclaration = sourceDeclarationForCatalogPath(
        authoredSourcePath,
        state.catalogProjection.sourceDeclarations,
        composition.sourceIdentityFor,
      );
      if (existing !== undefined && sourceDeclaration?.declaration.format === 'pack.json')
        if (
          (await readFile(sourceDeclaration.sourcePath, 'utf8').catch(() => undefined)) ===
          sourceDeclaration.declaration.sourceText
        )
          return existing;
      if (inFlightSourceRefresh === undefined)
        inFlightSourceRefresh = refreshAcceptedSource(authoredSourcePath).finally(
          () => (inFlightSourceRefresh = undefined),
        );
      await inFlightSourceRefresh;
      const declaration = sourceDeclarationForCatalogPath(
        authoredSourcePath,
        state.catalogProjection.sourceDeclarations,
        composition.sourceIdentityFor,
      );
      if (declaration?.declaration.format !== 'pack.json') {
        throw structuredPluginError({
          code: 'catalog-declaration-missing',
          expected: 'the accepted inventory to retain the authored Pack declaration',
          hint: 'rerun inventory before serving the authored Pack body',
          detail: { stage: 'route', sourcePath: authoredSourcePath },
        });
      }
      const refreshed = state.metaPackBodies.get(url);
      if (refreshed !== undefined) return refreshed;
      if (declaration.declaration.value.schemaVersion === '3.0.0') {
        const parsed = declaration.declaration.value;
        if (parsed.format !== 'direct') {
          throw structuredPluginError({
            code: 'pack-source-output-invalid',
            expected: 'a direct v3 Pack document for a materialized development route',
            hint: 'instances and ScriptablePack sources are published by the dynamic generation owner',
            detail: { stage: 'route', sourcePath: authoredSourcePath },
          });
        }
        const projected = projectDirectPackJson(parsed);
        throw structuredPluginError({
          code: 'pack-source-output-invalid',
          expected: 'the accepted direct Pack publication to stage a Pack v2 body and artifacts',
          hint: 'rebuild the direct Pack through the production publisher before requesting its body',
          detail: {
            stage: 'route',
            sourcePath: authoredSourcePath,
            packageId: projected.packageId,
          },
        });
      }
      const pack = {
        schemaVersion: '2.0.0' as const,
        kind: 'internal-text-package' as const,
        assets: declaration.declaration.value.assets.map((asset) => ({
          guid: asset.guid,
          kind: asset.kind,
          ...(asset.name === undefined ? {} : { name: asset.name }),
          payload: asset.payload,
          refs: asset.refs,
          artifacts: asset.artifacts ?? {},
        })),
      };
      const cooked = declaration.declaration.value.assets.some(
        (asset) => asset.execution === 'cooked',
      );
      if (cooked) {
        const refreshedAfterCook = state.metaPackBodies.get(url);
        if (refreshedAfterCook !== undefined) return refreshedAfterCook;
      }
      if (cooked) {
        throw structuredPluginError({
          code: 'pack-source-output-invalid',
          expected: 'an authored Pack source without cooked assets for direct transport',
          hint: 'move cooked assets into a registered producer or rebuild the authored Pack',
          detail: { stage: 'route', sourcePath: authoredSourcePath },
        });
      }
      return declaration.declaration.value.schemaVersion === '2.0.0'
        ? (declaration.declaration.sourceText ?? JSON.stringify(pack))
        : JSON.stringify(pack);
    }
    // A scoped imported Pack with an incomplete in-memory closure must go
    // through its producer after the DDC recovery read misses. Returning the
    // body here would make the package URL look healthy while its artifact
    // route still has no bytes to serve.
    if (existing !== undefined && !needsProducerRecovery) return existing;
    if (!url.startsWith(DEV_PACK_PREFIX) || !url.endsWith('.pack.json')) return undefined;

    const guid = url.slice(DEV_PACK_PREFIX.length, -'.pack.json'.length).toLowerCase();
    if (guid.includes('/')) return undefined;
    const metaPath = metaPathForGuid(state.catalogProjection.declarations, guid);
    if (metaPath === undefined) return undefined;

    await ensureVersionedMetaImport(metaPath, state.catalogProjection.declarations.get(metaPath));
    return state.metaPackBodies.get(url);
  }
  const importerRegistry = new ImporterRegistry();
  for (const imp of opts.importers ?? []) {
    importerRegistry.register(imp);
  }
  const registeredImporterKeys: ReadonlySet<string> = new Set(
    importerRegistry.registeredImporters(),
  );
  const fsForImport: ImportRunnerFs = {
    ...(composition.sourceIdentityFor === undefined
      ? {}
      : { sourceIdentityFor: composition.sourceIdentityFor }),
    async readSource(sourcePath: string) {
      try {
        const buf = await readFile(sourcePath);
        return { ok: true, value: new Uint8Array(buf) };
      } catch (e) {
        return { ok: false, error: e };
      }
    },
    async readSibling(sourcePath: string, uri: string) {
      try {
        const dir = dirname(sourcePath);
        const buf = await readFile(resolve(dir, uri));
        return { ok: true, value: new Uint8Array(buf) };
      } catch (e) {
        return { ok: false, error: e };
      }
    },
    ...importerRegistry.contextCapabilities(),
  };
  const serverLifecycle = createPluginServer({
    opts: composition,
    get transportBase() {
      return transportBase;
    },
    get projectDdcRoot() {
      return projectDdcRoot;
    },
    setProjectDdcRoot: (root) => {
      projectDdcRoot = root;
    },
    registeredImporterKeys,
    catalogVisibility: (input) => importerRegistry.shouldPublishCatalog(input),
    resetState: resetDevState,
    scopedPackageUrl,
    scopedCatalogEntry,
    scopedCatalogBody,
    state,
    setSourceRefresh: (refresh) => {
      refreshAcceptedSource = refresh;
    },
    callbacks: {
      publishAuthoredDevPacks,
      ensureMetaImport: ensureVersionedMetaImport,
      commitGeneration: async (candidate, signal) => {
        const committedImports: StagedImportPublication[] = [];
        const publicationSnapshots = new Map<string, ScriptablePackPublicationSnapshot>();
        for (const sourcePath of candidate.publicationCandidates.keys()) {
          publicationSnapshots.set(sourcePath, publicationStore.observe(sourcePath));
        }
        const rollback = async (): Promise<void> => {
          try {
            await Promise.all(
              committedImports.map((publication) => restoreImportPublication(publication)),
            );
            for (const [sourcePath, publication] of candidate.publicationCandidates) {
              publicationStore.discard(sourcePath, publication);
              const snapshot = publicationSnapshots.get(sourcePath);
              if (snapshot !== undefined) publicationStore.restore(sourcePath, snapshot);
            }
          } finally {
            // The production catch path calls discard after this callback rejects. These
            // candidates are already rolled back, so expose no second lifecycle mutation.
            candidate.pendingImportPublications.clear();
            candidate.publicationCandidates.clear();
          }
        };
        const assertOpen = (): void => {
          if (signal?.aborted === true) {
            throw structuredPluginError({
              code: 'stale-generation',
              expected: 'the production generation to remain current during commit',
              hint: 'retry the rebuild after the active generation settles',
              detail: { stage: 'commit', subject: 'production-generation' },
            });
          }
        };
        try {
          assertOpen();
          await state.artifactCompression?.prepare(candidate.devArtifactBodies.values());
          assertOpen();
          for (const [subject, input] of candidate.pendingImportPublications) {
            assertOpen();
            const staged = await stageImportPublication(input);
            if (!staged.ok)
              throw structuredPluginError({
                code: 'commit-failed',
                expected: 'DDC to stage the completed Meta import publication',
                hint: staged.error.hint,
                detail: { stage: 'commit', subject },
                cause: staged.error,
              });
            const publication = staged.candidate;
            committedImports.push(publication);
            const result = await commitImportPublication(publication);
            if (!result.ok) {
              // A newer generation may have superseded this lease while the
              // DDC commit was in flight.  Keep the strict DDC CAS outcome,
              // but classify the cancelled loser as stale so the caller can
              // retry the active generation instead of surfacing commit-failed.
              assertOpen();
              throw structuredPluginError({
                code: 'commit-failed',
                expected: 'DDC to commit every staged Meta import publication',
                hint: result.error.hint,
                detail: { stage: 'commit', subject },
                cause: result.error,
              });
            }
            // DDC owns the accepted revision. Install its rows into the private
            // complete generation, retaining later sources' prepared outputs.
            const publishedGuids = new Set(input.publishedGuids.map((guid) => guid.toLowerCase()));
            const acceptedRows = new Map(
              result.catalog
                .filter((row) => publishedGuids.has(row.guid.toLowerCase()))
                .map((row) => [row.guid.toLowerCase(), row]),
            );
            candidate.catalogProjection = {
              ...candidate.catalogProjection,
              entries: candidate.catalogProjection.entries.map(
                (row) => acceptedRows.get(row.guid.toLowerCase()) ?? row,
              ),
            };
            if (!result.transportPersisted) {
              for (const guid of publication.input.publishedGuids) {
                candidate.importedGuids.delete(guid.toLowerCase());
              }
              console.warn('[forgeax-pack] persist DDC pack failed:', {
                code: 'source-package-ddc-persistence-failed',
                guid: publication.input.guid,
                packageUrl: publication.input.transport?.path,
              });
            }
          }
          for (const [sourcePath, publication] of candidate.publicationCandidates) {
            assertOpen();
            const result = await publicationStore.commit(
              sourcePath,
              { envelope: publication },
              () => undefined,
            );
            if (!result.ok) {
              assertOpen();
              throw structuredPluginError({
                code: 'commit-failed',
                expected: 'DDC to commit every accepted authored Pack publication',
                hint: result.error.reason,
                detail: { stage: 'commit', sourcePath },
                cause: result.error,
              });
            }
          }
          assertOpen();
          await writeAssetBindingDeclaration(candidate.catalogProjection);
          invalidateBindingModules();
        } catch (error) {
          await rollback();
          throw error;
        }
      },
      discardPublications: (candidates) => {
        for (const [sourcePath, candidate] of candidates) {
          publicationStore.discard(sourcePath, candidate);
        }
      },
      discardImportPublications: async (candidates) => {
        candidates.clear();
      },
      ensureMetaPackBody,
      setCatalogDeltaPublisher: (publisher) => {
        publishCatalogDelta = publisher;
      },
    },
  });
  const buildLifecycle = createPluginBuild({
    opts: composition,
    get transportBase() {
      return transportBase;
    },
    registeredImporterKeys,
    catalogVisibility: (input) => importerRegistry.shouldPublishCatalog(input),
    importerRegistry,
    fsForImport,
    cookedCurrentProjection: COOKED_CURRENT_PROJECTION,
    directCurrentProjection: DIRECT_CURRENT_PROJECTION,
    authoredCookedCurrentProjection: AUTHORED_COOKED_CURRENT_PROJECTION,
    onPack: (url, body) => {
      state.metaPackBodies.set(url, body);
    },
    onPublication: (inventory) => {
      state.catalogProjection = inventory;
    },
    onInventory: async (inventory) => {
      // If build inventory arrives after a bound dev session, retain accepted
      // publication rows with their transport URLs and evidence.
      const acceptedPublications = state.catalogProjection.entries.filter(
        (entry) => entry.publication !== undefined,
      );
      if (serverLifecycle.runtimeBinding() === undefined && acceptedPublications.length === 0) {
        state.catalogProjection = inventory;
      } else if (acceptedPublications.length > 0) {
        const byGuid = new Map(
          inventory.entries.map((entry) => [entry.guid.toLowerCase(), entry] as const),
        );
        for (const entry of acceptedPublications) {
          byGuid.set(entry.guid.toLowerCase(), entry);
        }
        state.catalogProjection = {
          ...inventory,
          entries: [...byGuid.values()],
        };
      }
      await writeAssetBindingDeclaration();
    },
  });
  let viteCommand: PackViteConfig['command'];
  return {
    name: 'forgeax:pack',
    catalogSnapshot: () => state.catalogProjection.entries,
    async readPluginDefinitions() {
      const definitions = [];
      for (const row of state.catalogProjection.entries) {
        if (row.kind !== 'plugin') continue;
        const body =
          state.metaPackBodies.get(row.packageUrl) ??
          (await ensureMetaPackBody(row.packageUrl, serverLifecycle.runtimeBinding()));
        if (body === undefined)
          throw new TypeError(`${row.guid}: accepted plugin Pack body unavailable`);
        const pack = JSON.parse(body);
        const envelope = pack.assets.find((asset: { guid: string }) => asset.guid === row.guid);
        const asset = validatePluginAsset(envelope?.payload).unwrap();
        const { scopeId, generation, digest, outputSetDigest } = pack;
        definitions.push({
          definition: {
            guid: row.guid,
            asset,
            evidence: {
              kind: 'publication' as const,
              publication: { scopeId, generation, digest, outputSetDigest },
            },
          },
          sourcePath: row.sourcePath,
          refs: envelope.refs as string[],
        });
      }
      return definitions;
    },
    resolveId(source: string): string | null {
      if (source === VIRTUAL_RUNTIME_ID) return VIRTUAL_RUNTIME_ID;
      if (source === VIRTUAL_ASSETS_ID) return RESOLVED_VIRTUAL_ASSETS_ID;
      if (source === VIRTUAL_ASSETS_DTS_ID) return RESOLVED_VIRTUAL_ASSETS_DTS_ID;
      if (source === VIRTUAL_RUNTIME_TRANSPORT_ID) {
        return fileURLToPath(import.meta.resolve('@forgeax/engine-runtime'));
      }
      return null;
    },
    load(id: string): string | null {
      if (id === VIRTUAL_ASSETS_ID || id === RESOLVED_VIRTUAL_ASSETS_ID) {
        return assetBindingModuleSource(assetBindingCatalog());
      }
      if (id === VIRTUAL_ASSETS_DTS_ID || id === RESOLVED_VIRTUAL_ASSETS_DTS_ID) {
        return assetBindingDeclarationSource(assetBindingCatalog());
      }
      if (id !== VIRTUAL_RUNTIME_ID) return null;
      const activeBinding = serverLifecycle.runtimeBinding();
      return virtualRuntimeSource(
        viteCommand === 'serve' &&
          activeBinding !== undefined &&
          activeBinding.status !== 'transitioning'
          ? activeBinding
          : composition.runtimeBinding,
        viteCommand,
      );
    },
    configResolved(config: PackViteConfig): void {
      viteCommand = config.command;
      declarationTarget = resolve(
        config.root ?? process.cwd(),
        '.forgeax',
        'generated',
        'assets.d.ts',
      );
      if (config.command !== undefined) buildLifecycle.configResolved({ command: config.command });
      if (explicitTransportBase === undefined) transportBase = config.base;
    },
    ready: async () => {
      await serverLifecycle.ready();
      await state.artifactCompression?.prepare(state.devArtifactBodies.values());
    },
    rebind: serverLifecycle.rebind,
    rebuildCatalogInPlace: serverLifecycle.rebuildCatalogInPlace,
    runtimeBinding: serverLifecycle.runtimeBinding,
    configureServer: serverLifecycle.configureServer,
    buildStart: buildLifecycle.buildStart,
    generateBundle: buildLifecycle.generateBundle,
    closeBundle: async () => {
      serializedCatalog = undefined;
      await serverLifecycle.close();
      await buildLifecycle.closeBundle();
    },
  };
}

/** Package version string (debug tag). */
