export {
  type CookedMaterialRecord,
  collectMaterialCookRefs,
  createMaterialArtifactDigest,
  createMaterialCookIdentity,
  createMaterialProgramSetDigest,
  type MaterialCookArtifact,
  type MaterialCookProgram,
  type MaterialCookProgramContext,
  type MaterialCookRasterContext,
  type MaterialCookRayContext,
  type MaterialCookReceipt,
  type MaterialCookRecordError,
  type MaterialCookRefs,
  type MaterialCookWasmProvenance,
  materialLayerPlanIdentity,
  materialProgramContextForPass,
  materialProgramContextKey,
  projectCookedMaterialRecord,
  serializeCookedMaterialRecord,
  serializeMaterialCookReceipt,
  validateCookedMaterialRecord,
  validateMaterialCookProgramContext,
} from './evidence/material-cook.js';
