// apps/learn-render/3.model-loading/2.city-glb/src/index.ts
// Scratch demo: load the UE5 city_Sample_512.glb through the standard
// 4-step recipe (createApp -> configurePackIndex -> loadByGuid<SceneAsset>
// + instantiate -> app.start). Used to diagnose two reported issues:
//   1. texture tiling anomaly (glTF baseColorTexture.texCoord / UV-set select)
//   2. transparent materials rendering opaque (glTF alphaMode=BLEND)
//
// The glb + its generated .meta.json sidecar live in local-assets/ (gitignored).

import { createApp } from '@forgeax/engine-app';
import type { CanvasAppError } from '@forgeax/engine-app';
import { World } from '@forgeax/engine-ecs';
import { AssetGuid } from '@forgeax/engine-pack/guid';
import {
  Camera,
  createDevImportTransport,
  DirectionalLight,
  EngineEnvironmentError,
  PointLight,
  Transform,
} from '@forgeax/engine-runtime';
import type { SceneAsset } from '@forgeax/engine-types';
import { forgeaxBundlerAdapter } from 'virtual:forgeax/bundler';
import { addFirstPersonSystem } from '../../../../shared/src/learn-render-first-person';

// Generated by `forgeax-engine-remote-gltf import local-assets/city_Sample_512.glb`.
const CITY_SCENE_GUID = '019f221e-d014-716b-94d2-5bf3b3243806';
const PACK_INDEX_URL = '/pack-index.json';

const canvas = document.querySelector<HTMLCanvasElement>('#app');
if (canvas === null) {
  throw new Error("[city-glb] missing <canvas id='app'> in index.html");
}

function resizeCanvas(c: HTMLCanvasElement): void {
  c.width = window.innerWidth * devicePixelRatio;
  c.height = window.innerHeight * devicePixelRatio;
}
resizeCanvas(canvas);

void bootstrap(canvas);

async function bootstrap(target: HTMLCanvasElement): Promise<void> {
  const appRes = await createApp(
    target,
    {},
    { ...forgeaxBundlerAdapter(), importTransport: createDevImportTransport() },
  );
  if (!appRes.ok) {
    reportBootstrapError(appRes.error);
    return;
  }
  const app = appRes.value;
  const renderer = app.renderer;
  const world = app.world;

  app.onError((e) => {
    console.error('[city-glb] app.onError:', e.code, e.hint);
    const bus = (globalThis as unknown as {
      __learnRenderErrors?: Array<{ code: string; hint?: string }>;
    }).__learnRenderErrors;
    if (bus !== undefined) bus.push({ code: e.code, hint: e.hint });
  });

  const assets = renderer.assets;
  assets.configurePackIndex(PACK_INDEX_URL);

  const sceneGuidRes = AssetGuid.parse(CITY_SCENE_GUID);
  if (!sceneGuidRes.ok) {
    console.error('[city-glb] CITY_SCENE_GUID parse failed:', sceneGuidRes.error);
    return;
  }
  const sceneRes = await assets.loadByGuid<SceneAsset>(sceneGuidRes.value);
  if (!sceneRes.ok) {
    console.error('[city-glb] loadByGuid<SceneAsset> failed:', sceneRes.error.code, sceneRes.error.hint);
    const bus = (globalThis as unknown as {
      __learnRenderErrors?: Array<{ code: string; hint?: string }>;
    }).__learnRenderErrors;
    if (bus !== undefined)
      bus.push({
        code: sceneRes.error.code,
        ...(sceneRes.error.hint !== undefined ? { hint: sceneRes.error.hint } : {}),
      });
    return;
  }
  const sceneHandle = world.allocSharedRef('SceneAsset', sceneRes.value);
  const instRes = assets.instantiate<SceneAsset>(sceneHandle, world);
  if (!instRes.ok) {
    const errAny = instRes.error as { code: string; hint?: string };
    console.error('[city-glb] scene instantiate failed:', errAny.code, errAny.hint);
    return;
  }

  spawnLights(world);
  const cameraEntity = spawnCamera(world);
  if (cameraEntity === undefined) return;

  addFirstPersonSystem(app.world, app.renderer, {
    name: 'city-first-person',
    overrideBackend: undefined,
    moveSpeed: 12,
  });

  const startRes = app.start();
  if (!startRes.ok) {
    console.error('[city-glb] app.start failed:', startRes.error);
    return;
  }

  window.addEventListener('resize', () => {
    resizeCanvas(target);
    world.set(cameraEntity, Camera, { aspect: window.innerWidth / window.innerHeight });
  });

  console.warn(`[city-glb] backend=${renderer.backend} scene loaded via loadByGuid<SceneAsset>`);
  (window as unknown as Record<string, unknown>).__citySceneReady = true;

  if (app.remote) {
    console.warn(`[city-glb] remote eval on ws://localhost:${app.remote.port}/inspector`);
  }
}

function spawnLights(world: World): void {
  // Warm sun directional light.
  const d: [number, number, number] = [-0.4, -1.0, -0.35];
  const invLen = 1 / Math.sqrt(d[0] * d[0] + d[1] * d[1] + d[2] * d[2]);
  world.spawn({
    component: DirectionalLight,
    data: {
      directionX: d[0] * invLen,
      directionY: d[1] * invLen,
      directionZ: d[2] * invLen,
      colorR: 1.0,
      colorG: 0.97,
      colorB: 0.9,
      intensity: 3.5,
      mapSize: 2048,
      cascadeCount: 4,
      splitLambda: 0.75,
      cascadeBlend: 0.2,
      shadowDistance: 80,
      depthBias: 0.005,
    },
  });

  // A few fill point lights around the block (model bounds ~ +/-40 m).
  const pointDefs: Array<{
    pos: [number, number, number];
    color: [number, number, number];
    intensity: number;
    range: number;
  }> = [
    { pos: [0, 8, 0], color: [1.0, 0.95, 0.85], intensity: 200, range: 60 },
    { pos: [24, 6, 0], color: [0.7, 0.85, 1.0], intensity: 120, range: 40 },
    { pos: [-24, 6, 0], color: [1.0, 0.85, 0.6], intensity: 120, range: 40 },
  ];
  for (const pd of pointDefs) {
    world.spawn(
      {
        component: Transform,
        data: {
          pos: [pd.pos[0], pd.pos[1], pd.pos[2]], quat: [0, 0, 0, 1], scale: [1, 1, 1],},
      },
      {
        component: PointLight,
        data: {
          colorR: pd.color[0],
          colorG: pd.color[1],
          colorB: pd.color[2],
          intensity: pd.intensity,
          range: pd.range,
        },
      },
    );
  }
}

function spawnCamera(world: World): import('@forgeax/engine-ecs').EntityHandle | undefined {
  const aspect = window.innerWidth / window.innerHeight;
  const res = world.spawn(
    {
      component: Transform,
      data: {
        pos: [0, 3, 18], quat: [0, 0, 0, 1], scale: [1, 1, 1],},
    },
    {
      component: Camera,
      data: {
        fov: Math.PI / 3,
        aspect,
        near: 0.1,
        far: 500,
      },
    },
  );
  if (!res.ok) {
    console.error('[city-glb] spawnCamera failed:', res.error);
    return undefined;
  }
  return res.value;
}

function reportBootstrapError(err: CanvasAppError): void {
  if (err instanceof EngineEnvironmentError) {
    const inner = err.detail.webgpuError;
    const code = inner !== undefined && 'code' in inner ? inner.code : '<none>';
    console.error(`[city-glb] EngineEnvironmentError: webgpu inner=${code}`);
    return;
  }
  console.error(`[city-glb] ${err.code}: ${err.hint}`);
}

declare global {
  interface Window {
    __citySceneReady?: boolean;
    __learnRenderErrors?: Array<{ code: string; hint?: string }>;
  }
}
